- .github/workflows/main.yml
add checkpatch.pl code review action to github workflow.
> add checkpatch github workflow action

- service/capability/audio_player_agent.cc
Applying mandatory property changes to context field.
> capability: update audioplayer

- examples/oob_setup/README.md
- service/capability_manager.cc
It fix static analysis CodeStyle issues.
We ignore some issues which not found fix point or decided
to policy.
> fix static analysis issues about CodeStyle

- include/core/nugu_log.h
- include/core/nugu_uuid.h
- service/speech_recognizer.cc
- service/wakeup_detector.cc
- src/http2/http2_network.c
- src/http2/v1_ping.c
- src/nugu_directive.c
- src/nugu_directive_sequencer.c
- src/nugu_log.c
- src/nugu_network_manager.c
- src/nugu_uuid.c
Fixed issues reported by static analysis tools.
> fix static analysis issues

- include/interface/nugu_configuration.hh
- interface/nugu_configuration.cc
- service/capability/tts_agent.cc
update recently TTS Agent interface.
> capability: update TTS interface

- include/interface/capability/extension_interface.hh
- service/capability/extension_agent.cc
- service/capability/extension_agent.hh
update recently Extension Agent interface.
> capability: update Extension interface

- examples/standalone/delegation_listener.cc
- examples/standalone/delegation_listener.hh
- examples/standalone/nugu_sample.cc
- include/interface/capability/capability_interface.hh
- include/interface/capability/delegation_interface.hh
- include/interface/nugu_client.hh
- interface/nugu_client.cc
- service/capability/capability.cc
- service/capability/delegation_agent.cc
- service/capability/delegation_agent.hh
- service/capability_creator.cc
It add Delegation Interface for interaction with
user application if needed.
Be careful not to be included context of Delegation
Interface if not needed. It cause abnormal behavior
in general situation.
> add delegation interface

- examples/standalone/system_listener.cc
- examples/standalone/system_listener.hh
- include/interface/capability/system_interface.hh
- interface/nugu_client_impl.cc
- service/capability/capability.cc
- service/capability/system_agent.cc
- service/capability/system_agent.hh
The System agent code has been updated with the changes to the latest
specification.
> capability: update System interface

- service/capability/asr_agent.cc
- service/capability/asr_agent.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/capability.cc
- service/capability/capability.hh
- service/capability/delegation_agent.cc
- service/capability/delegation_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/capability/extension_agent.cc
- service/capability/extension_agent.hh
- service/capability/system_agent.cc
- service/capability/system_agent.hh
- service/capability/text_agent.cc
- service/capability/text_agent.hh
- service/capability/tts_agent.cc
- service/capability/tts_agent.hh
It adds implementations of capability initialize method in Capability
which is parent class of all CapabilityAgent.
Also, it defines getContextInfo method as virtual and implements
in Capability class.
> implements common method in Capability

- examples/standalone/extension_listener.cc
- examples/standalone/extension_listener.hh
- include/interface/capability/extension_interface.hh
- service/capability/extension_agent.cc
- service/capability/extension_agent.hh
add requestContext function to the listener and change function's
name from action to receiveAction.
> capability: modify extension listener

- examples/standalone/nugu_sample.cc
- include/interface/nugu_client.hh
- include/interface/nugu_configuration.hh
- interface/nugu_client.cc
- interface/nugu_client_impl.cc
- interface/nugu_client_impl.hh
- interface/nugu_configuration.cc
- service/speech_recognizer.cc
Synchronize with configuration and nugu_config and
set environment variables to higher priority.
> refactoring the configuration

- examples/standalone/delegation_listener.cc
- examples/standalone/delegation_listener.hh
- include/interface/capability/delegation_interface.hh
- service/capability/delegation_agent.cc
- service/capability/delegation_agent.hh
It change collecting way of user application context,
from set/remove to get method.
> delegation:change context handling

- service/capability/asr_agent.cc
Fixed an issue where media would play when requesting new DM
situation while using a media service such as Classic Manager.
> asrgent: fix the bug.

- service/capability/asr_agent.cc
- service/capability/asr_agent.hh
- service/capability/audio_player_agent.cc
- service/capability/capability.cc
- service/capability/capability.hh
- service/capability/delegation_agent.cc
- service/capability/display_agent.cc
- service/capability/extension_agent.cc
- service/capability/system_agent.cc
- service/capability/text_agent.cc
- service/capability/tts_agent.cc
refactoring the send event for code simplicity and readability.
> refactoring the send event

- service/capability/text_agent.cc
Fix to send all context informations.
> capability: fix text input event

- examples/standalone/nugu_sample.cc
- service/capability/delegation_agent.hh
It optimize nugu_sample code as using make_unique method and auto
to reduce duplicate code when create instances.
Also, it remove unused code in delegation_agent.hh
> Code optimization nugu_sample and delegation_agent

- examples/standalone/nugu_sample.cc
- examples/standalone/permission_manager.cc
- examples/standalone/permission_manager.hh
- include/interface/capability/capability_interface.hh
- include/interface/capability/location_interface.hh
- include/interface/capability/permission_interface.hh
- service/capability/capability.cc
- service/capability/capability.hh
- service/capability/location_agent.cc
- service/capability/location_agent.hh
- service/capability_creator.cc
It add LocationAgent for handling location infomation
which is composed by latitude and longitude.
It has to correlate with PermissionAgent in progress.
> add LocationAgent

- service/capability/asr_agent.cc
- service/capability/asr_agent.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/capability.cc
- service/capability/capability.hh
- service/capability/delegation_agent.cc
- service/capability/delegation_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/capability/extension_agent.cc
- service/capability/extension_agent.hh
- service/capability/permission_agent.cc
- service/capability/permission_agent.hh
- service/capability/system_agent.cc
- service/capability/system_agent.hh
- service/capability/text_agent.cc
- service/capability/text_agent.hh
- service/capability/tts_agent.cc
- service/capability/tts_agent.hh
Each Agent performs the same task when it receives
a directive from the directive sequencer. This part has
been modified to handle in base class Capability.
> capability: reduce common action

- service/capability/capability.cc
Permission.RequestAccessCompleted
> Add user action

- include/core/nugu_event.h
- src/network/http2/gateway_registry.cc
- src/network/http2/gateway_registry.h
- src/network/http2/http2_manage.c
- src/network/http2/http2_manage.h
- src/network/http2/http2_network.c
- src/network/http2/http2_network.h
- src/network/http2/http2_request.c
- src/network/http2/http2_request.h
- src/network/http2/v1_directives.cc
- src/network/http2/v1_directives.h
- src/network/http2/v1_event.c
- src/network/http2/v1_event.h
- src/network/http2/v1_event_attachment.c
- src/network/http2/v1_event_attachment.h
- src/network/http2/v1_ping.c
- src/network/http2/v1_ping.h
- src/nugu_event.c
- src/nugu_network_manager.c
This PR includes following 3 commits
- add set_token API to h2 network module 
- move payload generation api to nugu_event 
- add secs suffix to timeout parameter
> Network minor refactoring

- Doxyfile
It update Doxyfile version to 0.4.0
> update Doxyfile version

- include/core/nugu_network_manager.h
- service/capability/system_agent.cc
- src/network/dg_server.c
- src/network/dg_server.h
- src/network/dg_types.h
- src/network/http2/http2_network.c
- src/network/http2/v1_policies.cc
- src/nugu_network_manager.c
Refactoring the network module to prepare handoff connection feature
> Network minor refactoring for handoff

- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
It fix method call about location listener.
It adjust showing command prompt when network connection is progress.
In progress, it's not show prompt even if enter key is pressed.
It remove unnecessary included header.
> fix nugu_sample

- include/core/nugu_player.h
- include/interface/media_player_interface.hh
- include/interface/nugu_client.hh
- interface/nugu_client.cc
- interface/nugu_client_impl.cc
- interface/nugu_client_impl.hh
- service/media_player.cc
- service/media_player.hh
The application create and use nugu sdk's mediaplayer via nugu client.
The mediaplayer can play streaming, adaptive streaming and local
file contents.
> Support mediaplayer

- include/core/nugu_log.h
- plugins/portaudio.c
- src/network/http2/http2_request.c
- src/network/http2/v1_directives.cc
- src/nugu_log.c
Fixed a bug in which regular log messages would sometimes be treated as
raw logs due to thread issues.
> log: change raw log message handling

- doc/mainpage.dox
To clarify the module hierarchy change the doxygen module tree.
> doc: change doxygen module tree

- README.md
- clientkit/nugu_client_impl.cc
- core/capability/audio_player_agent.cc
- core/capability/audio_player_agent.hh
- core/capability/capability.cc
- core/capability/capability.hh
- core/capability/delegation_agent.cc
- core/capability/system_agent.cc
- include/base/nugu_focus.h
- include/base/nugu_media.h
- include/base/nugu_ringbuffer.h
- include/base/nugu_timer.h
- include/interface/media_player_interface.hh
- src/nugu_focus.c
- src/nugu_timer.c
Fix typo error in the header, source and README.md files
> fix typo error

- CMakeLists.txt
- externals/0001_curl_find_nghttp2.patch
- externals/0003_curl_ca_variables.patch
Update external modules
- nghttp2 v1.39.1 to v1.40.0 (November 15 2019) - https://github.com/nghttp2/nghttp2/releases
- curl v7.65.1 to v7.67.0 (November 6 2019) - https://curl.haxx.se/changes.html
> Update external modules

- examples/oob_setup/nugu_oob_server.py
add token refresh feature using refresh_token to oob server.
- refresh from command line: '-r' option
$ ./nugu_oob_server.py -r
- refresh from web: http://lvh.me:8080/refresh
> examples: add token refresh to oob server

- src/nugu_ringbuffer.c
- tests/test-nugu-ringbuffer.c
Fixed the bug occurred when the write index reached the maximum size
of the buffer.
> ringbuffer: fix the bug

- core/capability/system_agent.cc
- core/capability/system_agent.hh
- examples/standalone/capability/system_listener.cc
- examples/standalone/capability/system_listener.hh
- include/interface/capability/system_interface.hh
Add device's charging field in context for sending the device's
charging information to the Play.
System agent query information about battery to the device.
> Update System v1.1

- core/capability/extension_agent.cc
- core/capability/extension_agent.hh
- include/interface/capability/extension_interface.hh
It is available to send command data to Play(backend proxy)
whenever the application want.
> Update Extension v1.1

- core/capability/tts_agent.cc
- core/capability_manager.cc
- core/capability_manager.hh
- examples/standalone/capability/tts_listener.cc
- examples/standalone/capability/tts_listener.hh
- include/interface/capability/tts_interface.hh
Notifies the application when speech is canceled.
> TTS: add cancel event

- examples/oob_setup/nugu_oob_server.py
Add graceful shutdown when requesting token refresh via '-r' option
when running oob server.
> examples: add graceful shutdown to oob server

- include/interface/capability/audio_player_interface.hh
- src/core/capability/asr_agent.cc
- src/core/capability/asr_agent.hh
- src/core/capability/audio_player_agent.hh
- src/core/capability/capability.hh
- src/core/capability/display_agent.hh
- src/core/capability/tts_agent.hh
- src/core/display_render_assembly.hh
Fix build warnings on clang build.
> build: fix build warnings on clang

- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_manager_helper.cc
- src/core/capability_manager_helper.hh
It add method to change wakeup word in NuguClient.
ex)
NuguClient* nugu_client = new NuguClient();
nugu_client->setWakeupWord(/* user define */)
> add method to change wakeup word

- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_event_attachment.c
- src/base/network/http2/v1_ping.c
- src/base/nugu_log.c
This PR includes the following commits to improve network functionality.
- add hexdump to http2 body
- remove sync request 
- hide the http2_request_free
- add multipart to content type list
- add pause/resume to http2 request
> Network enhancement

- src/base/network/dg_server.c
- src/base/network/dg_server.h
- src/base/nugu_network_manager.c
Fix to stop the established ping interval when the ping fails.
> network: fix to stop ping when ping fails

- examples/CMakeLists.txt
- examples/simple_text/CMakeLists.txt
- examples/simple_text/text.cc
Add an example that simply works by sending a text command.
> examples: add simple text command example

- doc/mainpage.dox
- include/clientkit/speech_recognizer_interface.hh
- src/core/audio_recorder_manager.cc
> doc: update doxygen document

- examples/CMakeLists.txt
- examples/simple_asr/CMakeLists.txt
- examples/simple_asr/main_asr.cc
- examples/simple_text/CMakeLists.txt
- examples/simple_text/main_text.cc
Add an example that simply recognizes and operates by voice commands.
> examples: add simple asr example

- include/capability/asr_interface.hh
- include/capability/display_interface.hh
- include/capability/location_interface.hh
- include/capability/speaker_interface.hh
- include/capability/system_interface.hh
- include/capability/text_interface.hh
- include/capability/tts_interface.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/capability_interface.hh
- include/clientkit/network_manager_interface.hh
- include/clientkit/playsync_manager_interface.hh
- include/clientkit/speech_recognizer_interface.hh
- include/clientkit/wakeup_interface.hh
> Documentation

- include/base/nugu_equeue.h
- include/base/nugu_network_manager.h
- src/base/network/dg_server.c
- src/base/network/dg_types.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_event.h
- src/base/network/http2/v1_events.c
- src/base/network/http2/v1_events.h
- src/base/nugu_network_manager.c
Add event send result handler to notify the success/failure result to
application.
> network: add event send result handler

- include/base/nugu_plugin.h
- src/base/nugu_plugin.c
- tests/CMakeLists.txt
- tests/plugin_dummy.c
- tests/plugin_nugu.c
- tests/plugin_nugu_custom.c
- tests/test-nugu-plugin.c
Add nugu_plugin_get_symbol() API to get custom symbol from plugin
object.
> base: export dlsym API to nugu_plugin

- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
- src/capability/system_agent.cc
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
The application is responsible for deinitializing and then
deleting the class object.
> Capability: Remove deinitialize

- src/capability/audio_player_agent.cc
- src/capability/speaker_agent.cc
> Speaker: modify parser

- src/capability/mic_agent.cc
> MicAgent: modify parser

- include/base/nugu_directive.h
- src/base/network/http2/v1_directives.cc
- src/base/nugu_directive.c
- tests/test-nugu-directive.c
Support to read the group information each directive.
> Directive: Add directive groups

- examples/standalone/capability/speaker_listener.cc
- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
Divide the api between processing directive and application
control and fix the bug the context configuration.
> SpeakerAgent: modify API

- include/capability/asr_interface.hh
- include/clientkit/speech_recognizer_interface.hh
- include/clientkit/wakeup_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/audio_input_processor.cc
- src/core/audio_input_processor.hh
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
- src/core/wakeup_handler.hh
The NUGU SDK notifies the application of the result of the request
as the following function
> IASRHandler::startRecognition()
> IWakeupHandler::startWakeup()
> EPD, KWD: recorder mute

- src/base/CMakeLists.txt
- src/base/network/http2/http2_network.c
- src/base/network/http2/threadsync.c
- src/base/network/http2/threadsync.h
To make development easier, separated the thread synchronization logic
into a 'threadsync' module.
> network: add thread synchronization module

- include/capability/asr_interface.hh
- include/capability/speaker_interface.hh
- include/capability/text_interface.hh
- include/capability/tts_interface.hh
It add doxygen comments on default defined attribute values
of ASR,TTS,Text,Speaker interface.
> add comment on capability attribute

- include/base/nugu_network_manager.h
- include/clientkit/capability.hh
- src/base/network/dg_server.c
- src/base/network/dg_server.h
- src/base/network/dg_types.h
- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_event.h
- src/base/network/http2/v1_events.c
- src/base/network/http2/v1_events.h
- src/base/nugu_network_manager.c
- src/capability/system_agent.cc
- src/clientkit/capability.cc
Added synchronized event dispatch waiting to complete sending event
to server. (e.g. System.Disconnect event)
> network: add synchronized event send

- src/base/network/http2/v1_events.c
Currently only "/v1/event" supports sync events, so adds that
functionality to "/v1/events".
> network: add synchronized event send to /v1/events

- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
- src/capability/asr_agent.cc
- src/core/audio_input_processor.cc
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
add missing memory de-allocation nugu sample program to exit gracefully.
> examples: add graceful exit to sample program

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/mic_agent.cc
- src/capability/mic_agent.hh
- src/capability/tts_agent.cc
- src/core/capability_manager.cc
- send event with current agent's context information.
- send event `AudioPlayer.PlaybackPaused` only by user request
> Event Context

- examples/capability_injection/battery_agent.cc
- examples/capability_injection/battery_agent.hh
The developer can implement custom CapabilityAgent
using `Capability` class.
> Refactoring: capability injection example

- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
It adjust wake-up/listening commands like below.
w : start listening with wakeup
l : start listening
s : stop listening/wakeup.
It compose the separated class for managing capability and
related listener instances.
Each Capability is created by functional factory so,
if you want to get specific capability instance,
you can get it using by getCapability method.
> refactoring nugu sample adjust command

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- examples/standalone/nugu_sample_manager.cc
It optimize to compose SpeakerInfo in CapablityCollection.
> Optimization composing SpeakerInfo

- src/capability/asr_agent.cc
Add logic to handle error case of NotifyResult.
> capability: add asr NotifyResult error case

- src/base/network/dg_server.c
- src/base/network/http2/v1_ping.c
- src/base/network/http2/v1_ping.h
/v2/ping endpoint is added server to support /v2 API.
> network: add /v2/ping

- plugins/portaudio.c
Portaudio: fix the double free heap
> Portaudio double free heap

- include/clientkit/media_player_interface.hh
- include/clientkit/nugu_core_container_interface.hh
- src/core/media_player.cc
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- src/core/tts_player.cc
- src/core/tts_player.hh
The AudioPlayerAgent and TTSAgent should support the TTSPlayer
for attachment media.
> Add TTSPlayer

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
Refactoring nugu pcm player control in TTSAgent is
an alternative to TTSPlayer.
> Refactoring TTSAgent

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- Implement the attachment spec for AudioPlayerAgent.
> Audioplayer attachment

- include/clientkit/nugu_timer_interface.hh
- src/capability/asr_agent.cc
- src/capability/system_agent.cc
- src/capability/text_agent.cc
- src/core/nugu_timer.cc
- src/core/playsync_manager.cc
- tests/core-timer/nugu_timer_mock.cc
- tests/core-timer/test-core-NuguTimer.cc
NuguTimer supports timer based milli-second time unit.
> Timer: Update time unit

- examples/standalone/capability/text_listener.cc
- examples/standalone/capability/text_listener.hh
- examples/standalone/nugu_sample_manager.cc
- include/capability/text_interface.hh
- include/clientkit/capability.hh
- src/capability/asr_agent.cc
- src/capability/text_agent.cc
- src/capability/text_agent.hh
- src/clientkit/capability.cc
The TextAgent supports request & response mapping to the
applicaiton using dialog request id.
> TextAgent: Request & Response mapping #233

- examples/standalone/capability/tts_listener.cc
- include/capability/tts_interface.hh
- include/clientkit/capability.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/capability.cc
The TTSAgent supports request & response mapping to the
applicaiton using dialog request id.
> TTSAgent: Request & Response mapping #233

- examples/simple_asr/main_asr.cc
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- include/capability/asr_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
The ASRAgent supports request & response mapping to the
applicaiton using dialog request id.
> ASRAgent: Request & Response mapping #233

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
The AudioPlayerAgent supports request & response mapping to the
application using dialog request id.
> AudioPlayerAgent: Request & Response mapping nugu-developers#233

- examples/standalone/capability/system_listener.cc
- examples/standalone/capability/system_listener.hh
- include/capability/system_interface.hh
- src/capability/system_agent.cc
The SystemAgent supports request & response mapping to the
application using dialog request id.
> SystemAgent: Request & Response mapping nugu-developers#233

- include/clientkit/capability.hh
- src/capability/asr_agent.cc
Apply the RDRID #251 to ASRAgent.
> ASRAgent: Apply RDRID #251

- include/capability/tts_interface.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
Apply the RDRID #251 to TTSAgent.
> TTSAgent: Apply RDRID #251

- src/capability/text_agent.cc
Apply the RDRID #251 to TextAgent.
> TextAgent: Apply RDRID #251

- src/capability/mic_agent.cc
- src/capability/mic_agent.hh
Apply the RDRID #251 to MicAgent.
> MicAgent: Apply RDRID #251

- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
Apply the RDRID #251 to SpeakerAgent.
> SpeakerAgent: Apply RDRID #251

- src/capability/asr_agent.cc
- src/core/speech_recognizer.cc
- src/core/wakeup_detector.cc
- fix the timing issue
- improve performance
> Asr state timing

- src/capability/audio_player_agent.cc
- src/clientkit/capability.cc
Update the RDRID #251 to AudioPlayerAgent.
> AudioPlayerAgent: Update RDRID

- src/capability/system_agent.cc
Apply the RDRID #251 to SystemAgent.
> SystemAgent: Apply RDRID

- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- include/capability/asr_interface.hh
- include/clientkit/wakeup_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
- src/core/wakeup_handler.hh
Multi-wakeup feature is added ASR version 1.1.
> ASRAgent: support multi-wakeup feature

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Fixed event payloads that do not match specifications.
> AudioPlayer: fix the event payload

- src/base/network/http2/directives_parser.cc
- src/base/network/http2/directives_parser.h
- src/base/network/http2/v2_events.c
add custom debug message setter to directive parser to add http2
request information.
> network: add debug message to directive parser

- include/clientkit/capability_helper_interface.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
The capability name and version information is added to the all event.
> Capability: update event's context

- src/base/network/dg_server.c
- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
- src/base/network/http2/multipart_parser.c
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
fix multipart boundary control bug
> network: fix multipart issue

- include/clientkit/capability_helper_interface.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
Added API for accessing the wakeup word.
> Capability: Get wakeup keyword

- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- examples/standalone/capability_collection.cc
- include/capability/asr_interface.hh
- include/capability/speaker_interface.hh
- include/clientkit/wakeup_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/speaker_agent.cc
- src/capability/system_agent.cc
- src/capability/system_agent.hh
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
- src/core/wakeup_handler.hh
- SystemAgent
- SpeakerAgent
- TextAgent
- TTSAgent
- ASRAgent
> Sync specification

- plugins/gstreamer.c
The Discoverer utility has been modified to be used only
for streaming players and improved events and states for stabilization.
> Gstreamer: Stabilization

- examples/standalone/capability/speech_operator.cc
- include/base/nugu_prof.h
- include/clientkit/capability.hh
- src/base/network/dg_server.c
- src/base/network/http2/http2_request.c
- src/base/network/http2/v1_directives.c
- src/base/network/http2/v1_ping.c
- src/base/nugu_network_manager.c
- src/base/nugu_prof.c
- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
- src/core/speech_recognizer.cc
- src/core/wakeup_detector.cc
Marking has been added to the related source code to cover the entire
profiling point.
> profiling: add more profiling point to source

- examples/standalone/nugu_sample.cc
It remove the header which is included duplicated.
It upgrade the efficiency of string usages.
It change creating IWakeupHandler instance using by unique_ptr.
It remove no used NuguClientListener.
> Optimize nugu_sample code

- examples/standalone/capability/tts_listener.cc
- include/base/nugu_prof.h
- src/base/nugu_prof.c
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
add TTS failed and stopped profiling point.
> profiling: add TTS failed and stopped

- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
It make CommandMap for composing command text for displaying
and handling corresponding command about key input.
It apply move semantics on error(), info().
It change some static variables and methods to none-statics,
because, it sufficient to use by none-statics.
> Optimize NuguSampleManager

- include/base/nugu_log.h
- src/base/nugu_log.c
- src/base/nugu_prof.c
Add presets to easily configure log module combinations.
> base: add log module presets

- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
Modify the default volume step.
> Speaker: Set default volume step

- include/capability/asr_interface.hh
- include/clientkit/nugu_core_container_interface.hh
- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
It update to set EPD attribute like timeout, max duration by ASRAgent.
It transport to epd-module which exist in SpeechRecognizer.
> Update to set EPD attribute by ASRAgent

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- include/capability/audio_player_interface.hh
- include/clientkit/media_player_interface.hh
- plugins/gstreamer.c
- src/capability/audio_player_agent.cc
- src/core/media_player.cc
- Gstreamer: handle for underrun
- AudioPlayer: notify to report player's event
> Gstreamer underrun

- src/base/network/http2/http2_request.c
Fix the curl debug log for http2 request to prevent 'data_size > 0'
g_return_if_fail error log.
> base: fix http2 curl log

- examples/standalone/nugu_sample_manager.cc
- src/base/network/http2/http2_request.c
- src/base/nugu_log.c
- src/core/audio_input_processor.cc
- src/core/media_player.cc
fix the static analysis(clang-tidy) report
> Clang: fix the static analysis report

- src/capability/audio_player_agent.cc
Fixed a bug that the event `AudioPlayer.PlaybackPaused` was not sent
when the directive `AudioPlayer.Pause` was received through
the text command during media playback.
> AudioPlayerAgent: Fix the sendEventPlaybackPaused

- src/base/network/http2/http2_request.c
To identify multiple requests at the same time, add HTTP2Request
information to the curl debug log.
> network: add request info to curl log

- include/base/nugu_equeue.h
- include/base/nugu_network_manager.h
- include/clientkit/capability_helper_interface.hh
- include/clientkit/network_manager_interface.hh
- src/base/network/dg_types.h
- src/base/network/http2/v1_event.c
- src/base/network/http2/v2_events.c
- src/base/nugu_network_manager.c
- src/clientkit/network_manager_interface.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/network_manager.cc
Add a callback for receiving response directives for events.
> network: add event response callback

- src/base/nugu_event.c
Change the creation order of msg_id and dialog_id due to time issues
in analysis.
> base: change msg_id, dialog_id creation order

- examples/CMakeLists.txt
- examples/simple_play/CMakeLists.txt
- examples/simple_play/main_play.cc
Add an example of simply playing a media file without setting up
Capability agents or network token.
> examples: add simple media play

- plugins/gstreamer.c
Reserved seek is not work correctly according to player's state.
> Gstreamer: fix the seek bug

- include/clientkit/capability_helper_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
- src/core/audio_input_processor.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/speech_recognizer.cc
The user could send text or GUI command while recognizing speech.
These requirements have been improved and applied to ASRAgent.
> ASRAgent: Add cancel

- include/clientkit/capability_helper_interface.hh
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
It adjust sending network event result callback to CapabilityManager.
> Refactoring network callback handling

- examples/oob_setup/nugu_oob_server.py
add token revoke feature to sample oob server
> examples: add revoke feature to oob_server

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/xenial/changelog
- packaging/xenial/libnugu.lintian-overrides
> Release 0.10.1

- src/capability/tts_agent.cc
Add the currently playing TTS information to the Context.
> TTSAgent: Update version 1.2

- include/capability/system_interface.hh
- src/capability/system_agent.cc
The 'WITHDRAWN_USER' value has been added to the System.Revoke reason.
> capability: update System interface v1.2

- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/session_manager_interface.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/session_manager.cc
- src/core/session_manager.hh
It add SessionManager for managing session info
between client and play.
> Session: Add SessionManager

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
A Session interface for managing conversation sessions has been added
to remove the session id from ASRAgent.
> ASRAgent: Update version 1.2

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/session_agent.cc
It apply the changed DM session flow which is controlled
by SessionAgent and SessionManager.
> Session:Apply DM Session Flow

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
Fix typo error. 'grond' -> 'ground'
> capability: fix typo

- plugins/portaudio.c
To reduce the PCM write latency, changed the PortAudio stream I/O method
according to the document below.
http://portaudio.com/docs/v19-doxydocs/api_overview.html
According to the guide document, The 'Callback I/O Method' not suitable
for low performance targets.
> plugin: change PortAudio stream I/O method

- include/base/nugu_pcm.h
- plugins/portaudio.c
- src/base/nugu_pcm.c
- src/capability/speaker_agent.cc
The role has been changed to set the volume in the pcm player driver.
> Pcm: Export SetVolume to Driver

- include/clientkit/capability_helper_interface.hh
- include/clientkit/playstack_manager_interface.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test-core-playstack-manager.cc
It add PlayStackManager for managing playstack
info and handling layer according by policy.
Signed-off-by: kimhyungrok <hr97gdi@gmail.com>
> PlayStack: Add PlayStackManager

- examples/CMakeLists.txt
- examples/simple_tts/CMakeLists.txt
- examples/simple_tts/main_tts.cc
Add simple Text-To-Speech application to test the TTS feature.
> examples: add simple TTS application

- include/clientkit/session_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/session_manager.cc
- src/core/session_manager.hh
- tests/core/test-core-session-manager.cc
It change the management logic of session activation.
It adjust the session activating time from executing
ExpectSpeech mode to parsing that directive in ASRAgent.
Signed-off-by: kimhyungrok <hr97gdi@gmail.com>
> Session:Update SessionManager

- tests/core/test-core-playstack-manager.cc
- tests/core/test-core-session-manager.cc
It apply the fixture about creating instance of manager
and sub test data in PlayStackManager and SeesionManager test.
> tests:apply fixture in PlayStackManager,SessionManager test

- src/capability/asr_agent.cc
In previously, the LISTENING state is handled in READY condition,
but, it's not appropriated location.
So, it move the location of handling LISTENING state
to LISTENING condition, correctly.
> ASRAgent:change the location of handling listening state

- src/core/capability_manager.cc
Added debug log to capability manager for more easier analysis.
> CapabilityManager: Add debug log

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/xenial/changelog
- packaging/xenial/libnugu.lintian-overrides
> Release 0.20.0

- src/clientkit/capability.cc
fix double free issue when receive a not supported directive.
> capability: fix double free issue

- include/clientkit/session_manager_interface.hh
- src/core/session_manager.cc
- src/core/session_manager.hh
- tests/core/test_core_session_manager.cc
It add SessionManagerListener for receiving session active state.
> Session:add SessionManagerListener

- src/capability/speaker_agent.cc
There is missed the speaker type.
> SpeakerAgent: Fix the bug

- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/interaction_control_manager_interface.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/interaction_control_manager.cc
- src/core/interaction_control_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test_core_interaction_control_manager.cc
It add InteractionControlManager and related interface
for control interaction mode like multi-turn.
> interactionControl:add InteractionControlManager

- examples/standalone/nugu_sample.cc
- include/clientkit/capability.hh
- src/capability/asr_agent.cc
- src/clientkit/capability.cc
It apply multi-turn interaction mode in ASRAgent
as aliging with session active state.
It add log for check multi-turn start/finish in nugu_sample.
> interactionControl:apply multi-turn interaction mode

- examples/oob_setup/nugu_oob_server.py
The OAuth2 authentication specification has been changed as follows.
1. The 'scope' field is added to the response.
The server gives the scope information suitable for PoC information.
2. The 'data' field must be included in all requests.
For log analysis in the server, the data field must be included when
requesting token issuance and refresh.
> examples: add scope and data information

- examples/standalone/capability/sound_listener.cc
- examples/standalone/capability/sound_listener.hh
- include/capability/sound_interface.hh
- src/capability/sound_agent.cc
It add the DialogRequestId parameter in handleBeep method
which is declared in ISoundListener.
> SoundInterface:add DialogRequestId in handleBeep

- src/capability/display_agent.cc
DisplayAgent is supported Badge Object and UnifiedSearch1 directive.
The application could render this new feature.
> DisplayAgent: Update version 1.6

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/display_listener.cc
It unify the same output format about display render info
in display and audio player listener.
> nugu_sample:improve output log about display render

- examples/standalone/capability/speech_operator.hh
- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It change the structure of nugu_sample for maintenance conveniently.
It add the commands which are possible to control life cycle of SDK.
> sample:refactoring nugu sample

- plugins/portaudio_pcm_async.c
When the PCM is finished playing, the end-of-stream callback is called
after the delay through the `g_timeout_add()`, but there is a bug
called even after destroy.
To fix the bug, add code that removes the remaining timer when
calling the `pcm_destroy()` function.
> plugins: remove a pending timer when pcm_destroy

- tests/core/test_core_session_manager.cc
It add the reset test for SessionManager in unit test.
> Session:add reset test for SessionManager

- src/core/media_player.cc
- src/core/tts_player.cc
Media position check was performed by starting a timer at the time
when the media player object was created, but the timer was modified
to start at the time when the media player starts.
> Player: Modified using timer

- include/base/nugu_timer.h
- include/clientkit/nugu_core_container_interface.hh
- include/clientkit/nugu_timer_interface.hh
- src/base/nugu_timer.c
- src/capability/asr_agent.cc
- src/capability/system_agent.cc
- src/capability/text_agent.cc
- src/core/media_player.cc
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- src/core/nugu_timer.cc
- src/core/nugu_timer.hh
- src/core/playstack_manager.cc
- src/core/speech_recognizer.cc
- src/core/tts_player.cc
- src/core/wakeup_detector.cc
- tests/core/test_core_nugu_timer.cc
- tests/core/test_core_nugu_timer_mock.cc
- tests/test_nugu_timer.c
Complex APIs have been removed and functionality has been simplified.
> Timer: Refactoring nugu timer

- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
SpeakerAgent is added speaker group and default volume level information
to the context.
> SpeakerAgent: Update interface v1.2

- src/base/network/http2/v1_directives.c
fix typo error in the printf format string
> base: fix typo

- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It fix issues which are detected by static analysis(clang-tidy).
> test:fix static analysis issues

- tests/core/test_core_playsync_manager.cc
In some build environement like docker, if the PlaySyncManager test
is executed, it's failed because the timing issue is occurred
when manipulating timer.
So, as adjusting timer flow and thread check mechanism,
it fix not to fail PlaySyncManager test.
Also, it reduce test elapsed time from 0.66 sec to 0.23 on average.
> playsync:fix timer handling in PlaySyncManager test

- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
- include/clientkit/focus_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/session_agent.cc
- src/capability/tts_agent.cc
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test_core_focus_manager.cc
The NUGU is supported common sound policy to each device for
same and friendly user experience.
> FocusManager: Applied nugu sound policy

- src/capability/asr_agent.cc
There is two focus `ASRUser` and `ASRDM` in ASRAgent. The first focus is
activated when the user speech to AI speaker. The second focus is
activated when the user is requested to speech from AI speaker.
> ASRAgent: Modified the ASR focus

- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
ASRAgent supports EPD's timeout length adjustment function to support
long conversations.
> ASRAgent: Update interface v1.4

- .github/workflows/doxygen.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
add Github action scripts for Tag events
> add Github Action for tag

- include/capability/text_interface.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
It apply the text interface v1.5 spec.
- TextSourceFailed and TextRedirectFailed events are added.
> TextAgent:apply Text Interface v1.5 spec

- src/capability/utility_agent.cc
add missing `Capability::initialize()` API call.
> capability: add missing initialize to UtilityAgent

- .github/workflows/pull_request.yaml
- CMakeLists.txt
- src/core/directive_sequencer.cc
It add the Github Action about clang-tidy
which take charge of static analysis about source code.
> add Github Action about clang-tidy

- externals/0004_curl_ca_bundle_path.patch
- externals/patch_curl.sh
Added ca_bundle path for ssl certification.
> Curl: ca_bundle_path patch

- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/display_listener.hh
- examples/standalone/capability_collection.cc
- src/capability/display_agent.cc
- src/core/session_manager.cc
- tests/core/test_core_session_manager.cc
Because, session should be maintained with Display
it apply session flow in DisplayAgent.
> session:apply session flow in DisplayAgent

- src/capability/display_agent.cc
- src/capability/display_agent.hh
It apply the directive blocking policy about Display.
It would block Audio medium for all template directives.
> Display:apply directive blocking policy

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
It update to release playsync immediately,
if TTS.Stop directive is handled.
> TTS:handle TTS.Stop directive correctly

- .github/workflows/pull_request.yaml
It update clang-tidy action usage to use the shared action.
https://github.com/kimhyungrok/clang-tidy-action
> action:update clang-tidy action usage

- src/base/nugu_log.c
Fixed a problem in which PID was not output in the log. Previously,
the pid was limited to 5 digits, but if it exceeds 5 digits,
the problem occurs.
Earlier glibc version(<glibc 2.30) is support `gettid(void)` to get
thread id.
> Log: Fixed formatter for pid

- src/core/directive_sequencer.cc
- tests/core/test_core_directive_sequencer.cc
The log readability of Directive sequencer has been improved, and
test cases have been added to better understand the cancel behavior.
> core: improves log readability of sequencer

- src/base/nugu_event.c
- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
- src/capability/display_agent.cc
- src/capability/extension_agent.cc
- src/capability/mic_agent.cc
- src/capability/sound_agent.cc
- src/capability/speaker_agent.cc
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
- src/core/capability_manager.cc
The json data currently being sent is generated by `Json::StyledWriter`
for human readable log messages. However, it is not good in terms of
network efficiency, so change it to `Json::FastWriter`.
> capability: apply json minify

- src/base/network/http2/v2_events.c
Currently, when an event is created, the first boundary is transmitted
first, and data is transmitted according to subsequent requests.
The timing was modified so that the first boundary is sent together
when the first data is transmitted.
> base: fix send timing for 1st multipart boundary

- src/capability/mic_agent.cc
- src/capability/mic_agent.hh
It clean code about checking mic status and etc.
It compose the separate function for retrieving mic status text.
> MicAgent:clean code about checking status

- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test_core_focus_manager.cc
The focus holder is managed by specific focus type.
> Focus: modified focus holder

- src/capability/asr_agent.cc
It fix to update the asr intiator in case about EXPECT_SPEECH.
> ASRAgent:fix handling ASR Initiator about EXPECT_SPEECH

- include/capability/tts_interface.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
It add the addListener and removeListener API in ITTSHandler
which is possible to handle multiple ITTSListener objects.
> TTS:Add add/remove Listener API

- src/core/network_manager.cc
> add const to auto variables

- include/clientkit/wakeup_interface.hh
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
- src/core/wakeup_handler.hh
It add the changeModel API in IWakeupHandler
for changing wakeup model file dynamically.
As the model is divided by directory,
it has to compose each model directory separately.
> Wakeup:Add API for changing model

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the API for releasing current sync unconditionally.
> PlaySync:Add release sync API

- include/clientkit/capability_helper_interface.hh
- include/clientkit/routine_manager_interface.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/routine_manager.cc
- src/core/routine_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test_core_routine_manager.cc
It add the RoutineManager for handling routine play.
> Routine:Add RoutineManager

- examples/oob_setup/nugu_oob_server.py
It add a feature which is able to get OAuth2 token by client credentials.
It remove not used element in OAuth info like pocId.
It adjust UI and correct checking elements of token.
> oob_server:Add OAuth2 client credentials

- packaging/bionic/changelog
- packaging/xenial/changelog
It fix the changelog format error.
> Release 1.2.0:fix changelog format

- src/capability/nudge_agent.cc
- src/capability/nudge_agent.hh
It fix the typo error in NudgeAgent.
> Nudge:fix typo error

- src/capability/audio_player_agent.cc
There is some interval between receiving event response and media
direct access control, and it cause unexpected action. So parsing
action is synced with audioplayer's contenxt.
> AudioPlayerAgent: sync with context

- include/capability/display_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
There is added new display template type `TabExtension` and the
interface is updated `elementSelected` that is added postback param.
> Capability: Display interface v1.8

- src/capability/text_agent.cc
There is an incorrect json format used.
> TextAgent: Fixed the bug

- include/capability/routine_interface.hh
- src/capability/routine_agent.cc
- src/capability/routine_agent.hh
It add the startRoutine API which is possible to execute Routine
from external component if the data is sent correctly.
It apply the referrer dialog id on sending events.
> Routine:apply schedule routine feature

- CMakeLists.txt
- plugins/CMakeLists.txt
- plugins/gstreamer_recorder.c
- plugins/portaudio_recorder.c
`Gstreamer Recorder` is added to plugin and `Portaudio Recorder` is
set default recorder driver.
Signed-off-by: nugulinux <nugulinux@gmail.com>
> plugin: gstreamer recorder

- include/capability/capability_factory.hh
- include/capability/phone_call_interface.hh
- src/capability/capability_factory.cc
- src/capability/phone_call_agent.cc
- src/capability/phone_call_agent.hh
PhoneCallAgent is available to dial, hangup and answer the call.
Please see document as below.
<https://developers-doc.nugu.co.kr/nugu-sdk/capability-interface/phonecall>
> Capability: Add PhoneCall interface v1.2

- tests/core/test_core_playsync_manager.cc
It remove the redundant test assertions.
It adjust the TIMER_DOWNSCALE_FACTOR for improving test speed.
> Playsync:clean PlaySyncManager test code

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- src/capability/audio_player_agent.cc
It update to handle ShowLyrics and HideLyrics directives wholly,
which send the related result events.
> AudioPlayer:update to handle directives about Lyrics

- include/capability/capability_factory.hh
- include/capability/message_interface.hh
- src/capability/capability_factory.cc
- src/capability/message_agent.cc
- src/capability/message_agent.hh
MessageAgent is available to send and read the message. Please see
document as below.
<https://developers-doc.nugu.co.kr/nugu-sdk/capability-interface/message>
> Capabiliy: Add Message interface v1.5

- include/clientkit/routine_manager_interface.hh
- src/clientkit/capability.cc
- src/core/routine_manager.cc
- src/core/routine_manager.hh
- tests/core/test_core_routine_manager.cc
It add the isConditionToFinishAction API in RoutineManager
for updating check condition about finishing action.
> Routine:Update check about finishing action

- examples/oob_setup/nugu_oob_server.py
- examples/standalone/nugu_sample_manager.hh
- plugins/gstreamer_pcm.c
- src/base/network/http2/v1_ping.c
- src/base/nugu_network_manager.c
Fixed some issues reported in the Codacy static analysis tool.
> fix static analysis tool report issues

- examples/standalone/bluetooth_status.cc
- examples/standalone/bluetooth_status.hh
- examples/standalone/capability/bluetooth_listener.cc
- examples/standalone/capability/bluetooth_listener.hh
- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
- include/capability/bluetooth_interface.hh
- include/capability/capability_factory.hh
- src/capability/bluetooth_agent.cc
- src/capability/bluetooth_agent.hh
- src/capability/capability_factory.cc
The `BluetoothAgent` is available to handle bluetooth such as set
discoverable mode and media control.
https://developers-doc.nugu.co.kr/nugu-sdk/capability-interface/bluetooth
> Capability: Bluetooth interface v1.1

- .cppcheck_suppress.txt
- .github/workflows/pull_request.yaml
Add cppcheck static analysis to pull_request action.
Note that this will not affect the build result.
> add cppcheck tool to pull_request action

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It update the releaseSyncUnconditionally API
which is possible to release the specific playstack.
> PlaySync:Update releaseSyncUnconditionally API

- src/capability/text_agent.cc
- src/capability/text_agent.hh
It apply the Text interface v1.6 spec.
* ExpectTyping directive added
> Text:Apply Text interface v1.6

- examples/profiling/README.md
- examples/profiling/main_prof.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
fix model path `/var/lib/model` to `/usr/share/nugu/model`
> examples: fix model path

- src/capability/message_agent.cc
- src/capability/message_agent.hh
It update to finish InteractionControl after sending the matched event.
* SendCandidates : CandidatesListed
* GetMessage : GetMessageSucceeded,GetMessageFailed
> Message:Update to finish InteractionControl

- src/capability/tts_agent.cc
It fix to clear the playstackctl_ps_id,
if the current playstack or focus is released.
When handling TTS.Stop directive, if the playstackctl_ps_id is empty
it retrieve that value from playStackControl in payload
for releasing correct playstack.
> TTS:Fix playStackControl management

- examples/standalone/capability/chips_listener.cc
- examples/standalone/capability/chips_listener.hh
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/chips_agent.cc
- src/capability/chips_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/nudge_agent.cc
- src/capability/nudge_agent.hh
- src/capability/routine_agent.cc
- src/capability/routine_agent.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/routine_manager.cc
- src/core/routine_manager.hh
It change the defining location of constant variables from constructor
to header for improving performance of initialization.
> Change defining location of constant variables

- plugins/gstreamer_pcm.c
Replaced capsfilter with rawaudioparse + audioconvert element to
support volume element properly.
> plugins: fix gstreamer pcm pipeline

- plugins/gstreamer_recorder.c
Add the following 2 features to the GStreamer recorder plugin that
was in PortAudio recorder plugin.
- Dump recording data to a file
- Read recording data from dumped files instead of microphones
> plugins: add dump feature to gstreamer recorder

- examples/standalone/capability_collection.cc
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It update to mute TTS by command.
> nugu_sample:Handle TTS mute

- examples/capability_injection/main_capability_injection.cc
- examples/profiling/main_prof.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/simple_text/main_text.cc
- examples/simple_tts/main_tts.cc
add type2 authentication(on-demand connection) support to sdk simple
examples.
> examples: add type2 authentication support

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
Because the construction of capability factory in CapabilityCollection
is very long and so many duplicated codes exist,
it reduce codes as possible using by template function.
> nugu_sample:Refactor composing capability factory

- examples/standalone/capability/bluetooth_listener.cc
- examples/standalone/capability/bluetooth_listener.hh
- examples/standalone/capability/capability_listener.cc
- examples/standalone/capability/capability_listener.hh
- examples/standalone/capability/chips_listener.hh
- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/display_listener.hh
- examples/standalone/capability/extension_listener.cc
- examples/standalone/capability/extension_listener.hh
- examples/standalone/capability/mic_listener.hh
- examples/standalone/capability/session_listener.hh
- examples/standalone/capability/sound_listener.hh
- examples/standalone/capability/speaker_listener.hh
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- examples/standalone/capability/system_listener.hh
- examples/standalone/capability/text_listener.hh
- examples/standalone/capability/tts_listener.cc
- examples/standalone/capability/tts_listener.hh
- examples/standalone/capability_collection.cc
It add the CapabilityListener which is to be the base class of
all various capability listeners.
It add the setCapabilityHandler method in CapabilityListener for setting
the related capability handler to the derived capability listener.
> nugu_sample:Add CapabilityListener

- examples/standalone/capability/bluetooth_listener.cc
- examples/standalone/capability/bluetooth_listener.hh
- examples/standalone/capability/extension_listener.cc
- examples/standalone/capability/extension_listener.hh
- examples/standalone/nugu_sdk_manager.cc
- include/capability/bluetooth_interface.hh
- include/capability/extension_interface.hh
- src/capability/bluetooth_agent.cc
- src/capability/bluetooth_agent.hh
- src/capability/extension_agent.cc
- src/capability/extension_agent.hh
The application stores and manages the context information for the
capability, and the agent requests it and uses the context information.
> Capability: Modified Context

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
It optimize composing capability factory in CapabilityCollection
by reducing overloaded template function.
> nugu_sample:Optimize composing capability factory

- include/clientkit/nugu_runner.hh
- src/clientkit/nugu_runner.cc
- tests/clientkit/CMakeLists.txt
- tests/clientkit/test_clientkit_nugu_runner.cc
NuguRunner supports thread safety by working in GMainLoop.
> Thread-safety: NuguRunner

- include/clientkit/nugu_runner.hh
- src/clientkit/nugu_runner.cc
NuguRunner now uses a single callback that extracts methos from the map
and excutes them.
> clientkit: improve NuguRunner's performance

- include/base/nugu_http.h
- src/base/CMakeLists.txt
- src/base/network/http2/http2_request.c
- src/base/nugu_curl_log.c
- src/base/nugu_curl_log.h
- src/base/nugu_http.c
- tests/CMakeLists.txt
- tests/test_nugu_http.c
- tests/test_server.js
add HTTP request(get/post/put/delete) API to handle token update.
> base: add HTTP request API

- include/clientkit/nugu_http_rest.hh
- src/clientkit/nugu_http_rest.cc
- tests/clientkit/CMakeLists.txt
- tests/clientkit/test_clientkit_http_rest.cc
add NuguHttpRest class to support HTTP request.
> clientkit: add HTTP rest API

- src/base/nugu_audio.c
Export nugu audio function api.
> base: export API

- include/capability/chips_interface.hh
- src/capability/chips_agent.cc
- src/capability/chips_agent.hh
It add the addListener/removeListener API in IChipsHandler
for supporting multi listeners.
> Chips:update to support multi listeners

- include/clientkit/dialog_ux_state_aggregator_interface.hh
- src/clientkit/dialog_ux_state_aggregator.cc
- src/clientkit/dialog_ux_state_aggregator.hh
- tests/clientkit/CMakeLists.txt
- tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
It add the DialogUXStateAggregator for notifying the DialogUXState
which is composed by combination of ASR, TTS, Chips info.
> clientkit: add DialogUXStateAggregator

- src/capability/text_agent.cc
It update the Text interface version to 1.7.
> Text:update Text interface 1.7

- examples/oob_setup/nugu_oob_server.py
It add the jti field on OAuth result.
> nugu_oob_server: add jti on result

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/focal/changelog
- packaging/focal/libnugu.lintian-overrides
- packaging/xenial/changelog
- packaging/xenial/libnugu.lintian-overrides
> Release 1.7.1

- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
It compose the SpeechRecognizerAggregator in NuguClientImpl.
It add the getSpeechRecognizerAggregator API for retrieving instance.
It provide builder setWakeupModel to setup SpeechRecognizerAggregator.
> NuguClient: compose SpeechRecognizerAggregator

- include/clientkit/speech_recognizer_aggregator_interface.hh
- src/clientkit/nugu_client_impl.cc
- src/clientkit/speech_recognizer_aggregator.cc
- src/clientkit/speech_recognizer_aggregator.hh
- tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
As considering the case that the WakeupHandler is setup by user,
It expose the setWakeupHandler API in ISpeechRecognizerAggregator.
> SpeechRecognizerAggregator: expose setWakeupHandler API

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/focal/changelog
- packaging/focal/libnugu.lintian-overrides
- packaging/jammy/changelog
- packaging/jammy/libnugu.lintian-overrides
- packaging/xenial/changelog
- packaging/xenial/libnugu.lintian-overrides
> Release 1.7.2

- CMakeLists.txt
It apply the LTO (link time optimization) option.
This option is applied to all the targets.
> build: apply LTO option

- .github/workflows/pull_request.yaml
It update the cppcheck ubuntu target from bionic to focal.
> build:update cppcheck ubuntu target

- examples/oob_setup/nugu_oob_server.py
- packaging/bionic/control
- packaging/focal/control
- packaging/jammy/control
It update the nugu_oob_server which is activated on python3.
It update the libnugu-examples package depends about python.
> examples: update nugu_oob_server

- plugins/gstreamer.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
There is `heap-use-after-free` issue when the application is terminated
during playing or recording. Callbacks registered with gstreamer can
refer to addresses that have already been freed, unless the signal is
disconnected.
> gstreamer: disconnect signal

- .github/workflows/codeql-analysis.yaml
add CodeQL static analysis to to find potential vulnerabilities.
> build: add CodeQL static analysis

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/focal/changelog
- packaging/focal/libnugu.lintian-overrides
- packaging/jammy/changelog
- packaging/jammy/libnugu.lintian-overrides
> Release 1.7.3

- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
add macos build to pull_request and push action
> build: add github action for macos

- plugins/gstreamer_recorder.c
Recording using gstreamer in macOSX not support 16000 rate directly, so need the `audioresample` element to resample the raw data.
This patch add both `audioconvert` and `audioresample` element to gstreamer recorder pipeline and change `caps_filter` link order.
> plugins: add audioresample to gstreamer plugin

- .checkpatch.conf
- plugins/gstreamer.c
- plugins/opus.c
- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/multipart_parser.c
- src/base/network/http2/multipart_parser.h
Fixed some issues reported in the checkpatch tool.
> fix checkpatch tool report issues

- include/clientkit/nugu_auth.hh
- src/clientkit/nugu_auth.cc
- tests/clientkit/test_clientkit_auth.cc
Apply following changes
- clientkit: add HTTP response data to Auth request
> Apply changes

- plugins/gstreamer_pcm.c
- plugins/portaudio_pcm_async.c
fix the `heap-use-after-free` issue.
> plugin: fix runtime error

- plugins/CMakeLists.txt
- plugins/filedump.c
- plugins/filereader.c
add a feature to read audio data files and perform speech recognition without using audio framework.
> plugin: file reader

- plugins/filereader.c
The filereader is consumed the written audio data from file.
> plugin: improve filereader

- include/clientkit/nugu_auth.hh
- src/clientkit/nugu_auth.cc
> auth: refactoring

- .github/workflows/codeql-analysis.yaml
add rapidjson-dev package to dependency list
> ci: fix codeQL build error

- .github/workflows/push.yaml
Add CI script for Black Duck analysis.
> ci: add black duck analysis

- .github/workflows/pull_request.yaml
Reuse workflows from nugulinux/.github repository.
> action: fix script to use reuse workflows

- src/core/playsync_manager.cc
The std::out_of_range exception may not be caught in some environments.
(It causes the Unwind_RaiseException and such app is terminated.)
So, it changed to check an element existence before retrieving.
> playsync: improve exception handling

- include/base/nugu_audio.h
- src/base/nugu_audio.c
add function `nugu_audio_get_attribute`.
> base: nugu audio

- nugu.pc.in
add `nugu-kwd` and `nugu-epd` to requires dependency in `nugu.pc`
> add nugu-kwd and nugu-epd to pc file dependency

- packaging/bionic/control
- packaging/focal/control
- packaging/jammy/control
add `nugu-kwd`, `nugu-epd` devel packages to `libnugu-dev` depends.
> packaging: add dev dependency

- .github/workflows/codeql-analysis.yaml
Change `autobuild` to manual build to fix build errors.
> action: fix CodeQL action to use manual build

- include/capability/audio_player_interface.hh
- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- include/clientkit/network_manager_interface.hh
- include/clientkit/nugu_core_container_interface.hh
- include/clientkit/nugu_timer_interface.hh
- include/clientkit/playsync_manager_interface.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- src/core/nugu_timer.cc
- src/core/nugu_timer.hh
It fix the incorrect method documentation correctly.
Also, it fix the variable not matched with coding convention.
> fix the method documentation

- src/clientkit/nugu_client_impl.cc
The example `nugu_simple_text` is hangup during initializing sdk.
> clikentkit: fix hangup

- plugins/CMakeLists.txt
- plugins/filedump.c
- plugins/filereader.c
- plugins/gstreamer.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
- plugins/opus.c
- plugins/opus_encoder.c
- plugins/portaudio.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
- plugins/speex.c
Modified the plugin name string to be used by obtaining the value from the plugin instead of using it directly.
> plugin: fix plugin name

- src/capability/tts_agent.cc
Matching memory allocation and deallocation.
> sdk: memory deallocation

- src/base/nugu_plugin.c
- tests/CMakeLists.txt
- tests/plugin_nugu_custom.c
- tests/test_nugu_plugin.c
Fix the nugu_plugin_* API to support WIN32 platform.
> base: fix nugu_plugin module to support WIN32

- src/base/nugu_log.c
The `syslog` is not supported in the WIN32 platform.
> base: disable syslog in WIN32 platform

- plugins/gstreamer.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
- src/core/audio_input_processor.cc
- tests/clientkit/test_clientkit_nugu_runner.cc
add `_WIN32` macro check to existing `__MSYS__` macro check logic
> add _WIN32 to existing __MSYS__ guard

- tests/CMakeLists.txt
- tests/test_nugu_plugin.c
Fix the test plugin filename prefix
> tests: fix plugin testcase

- src/clientkit/dialog_ux_state_aggregator.hh
- src/clientkit/speech_recognizer_aggregator.hh
- src/core/directive_sequencer.hh
- src/core/focus_manager.hh
- src/core/interaction_control_manager.hh
- src/core/media_player.hh
- src/core/nugu_timer.hh
- src/core/playstack_manager.hh
- src/core/playsync_manager.hh
- src/core/routine_manager.hh
- src/core/session_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test_core_focus_manager.cc
divide mock library and executable for PDB and exports some core APIs for msvc testing.
> tests: support msvc

- src/core/speech_recognizer.cc
fix following codes to support WIN32
- change variable-length array to `calloc()`
- change `nanosleep` to `Sleep()`
> core: fix SpeechRecognizer to support WIN32

- src/core/capability_manager.cc
It fix not to handle higher capability version when handling directive.
> fix capability version check

- src/capability/audio_player_agent.cc
It update to compose rendering info when parsing play directive.
> improve AudioPlayer playsync handling

- src/capability/audio_player_agent.cc
> fix bug: seek time unit

- src/capability/audio_player_agent.cc
media player's seek use the second unit.
> capability: fix bug

- CMakeLists.txt
- Doxyfile
- packaging/bionic/changelog
- packaging/bionic/libnugu.lintian-overrides
- packaging/focal/changelog
- packaging/focal/libnugu.lintian-overrides
- packaging/jammy/changelog
- packaging/jammy/libnugu.lintian-overrides
- packaging/opkg/control
> Release 1.7.6
