nugu-developers/nugu-linux

- interface/nugu_client_impl.cc
- interface/nugu_client_impl.hh
Eliminates an issue when nugu client repeatedly calls
initialize and deinitialize.
> hangup issue fix.

- service/audio_input_processor.cc
- service/audio_input_processor.hh
- service/speech_recognizer.cc
- service/speech_recognizer.hh
- service/wakeup_detector.cc
- service/wakeup_detector.hh
Because SpeechRecognizer and WakeupDetector had so many
common variables and methods, it needed to do refactoring.
As defining parent class of both to AudioInputProcessor
and inheriting this, it could remove so many duplicated codes.
> Refactoring SpeechRecognizer and WakeupDetector

- CONTRIBUTING.md
- README.md
Move the doc/contributing.md to repository's root directory to make
Github recognize the contribution document. Because the Github can
recognize only if the document is in 'docs/' or root.
> rename the contributing.md

- include/interface/capability/capability_observer.hh
- include/interface/media_player_interface.hh
- include/interface/network_manager_interface.hh
- include/interface/nugu_configuration.hh
- include/interface/wakeup_interface.hh
- interface/nugu_configuration.cc
- service/capability/asr_agent.cc
- service/capability_manager.cc
- service/speech_recognizer.cc
- service/wakeup_detector.cc
Because namespace of NuguConfig is NuguClientKit, it cause
cross depenent between NuguCore and NuguClientKit.
So, it change namespace of NuguConfig from NuguClientKit
to NuguInterface.
> adjust namespace of NuguConfig

- .travis.yml
Fix the .travis.yml to build arm64 and armhf architectures on push.
Below is the full build matrix. (6 items)
- xenial + amd64
- xenial + arm64
- xenial + armhf
- bionic + amd64
- bionic + arm64
- bionic + armhf
However, travis runs 5 parallel builds at a time, so the build for PR
only builds amd64 to prevent build delays.
> build: fix travis configuration

- service/capability/display_agent.cc
- service/playsync_manager.cc
- service/playsync_manager.hh
In display interface, because it's possible to setup
custom duration time of displaying contents, it update
PlaySyncManager for handling this feature.
> apply custom duration in PlaySyncManager

- include/interface/capability/capability_interface.hh
- service/capability/capability.hh
- service/capability_manager.cc
- service/capability_manager.hh
capability agent can support same major version of directive.
capability manager check the directive's version before pass
it to each the capability agent.
> capability manager: check directive version

- service/playsync_manager.cc
- service/playsync_manager.hh
It change location of displaying context stack logs
in PlaySyncManager from stdout to nugu_debug.
Also, it change typedef syntax about DisplayRenderer and
TimerCallbackParam struct to using alias.
> adjust log about context stack

- service/capability/asr_agent.cc
- service/capability/text_agent.cc
- service/capability/text_agent.hh
update recently Text Agent interface and modify access
to ASR variables with ambiguous names.
> capability: update Text interface

- include/interface/media_player_interface.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/media_player.cc
Agent doesn't send an event(PlaybackResumed) when playing after
receiving the directive and modify the mediaEventReport.
The media player supports play with seek now.
> capability: update AudioPlayer interface

- include/interface/nugu_configuration.hh
- interface/nugu_configuration.cc
Even if you deinitalize the nugu client, you should not modify
the defaults because they will remain in memory.
> config: fix the bug.

- service/capability/asr_agent.cc
send attachment event by is_end flag even if the data is empty.
> fix the bug.

- include/interface/nugu_configuration.hh
- interface/nugu_client_impl.cc
- interface/nugu_configuration.cc
- src/http2/gateway_registry.cc
- src/http2/http2_request.c
Because of server policy changes, server_type is no longer required. So
deleted this key and modified the full registry URL to be configurable
instead.
> config: remove server_type

- examples/standalone/audio_player_listener.cc
- examples/standalone/audio_player_listener.hh
- examples/standalone/display_listener.cc
- examples/standalone/display_listener.hh
- include/interface/capability/audio_player_interface.hh
- include/interface/capability/delegation_interface.hh
- include/interface/capability/display_interface.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/playsync_manager.cc
- service/playsync_manager.hh
It change handling display context which is cleared
after checking user application's decision.
If user decided to clear immediately, display context is
cleared in check time. If not, you has to clear manually.
> update handling display context

- service/capability/audio_player_agent.cc
- service/capability/display_agent.cc
the template type has been unified as belows:
> AudioPlayer.Template1
> AudioPlayer.Template2
> Display.FullText1
> Display.FullText2
> ...
> template: unified the template type

- interface/nugu_client_impl.cc
- service/capability_creator.cc
- service/capability_creator.hh
It change policy about creating Capability Agent instance.
It defined required agents for operating SDK and
if user app did not add that agents, sdk create it automatically.
It needs to define what required agents are.
It currently, ASR,TTS,AudioPlayer,System Agents are included.
> Update creating CapabilityAgent Instance Policy

- examples/standalone/audio_player_listener.cc
- examples/standalone/audio_player_listener.hh
- examples/standalone/display_listener.cc
- examples/standalone/display_listener.hh
- examples/standalone/extension_listener.cc
- examples/standalone/nugu_sample.cc
- examples/standalone/tts_listener.cc
- examples/standalone/tts_listener.hh
- include/interface/capability/audio_player_interface.hh
- include/interface/capability/display_interface.hh
- include/interface/capability/tts_interface.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/capability/tts_agent.cc
- service/capability/tts_agent.hh
- service/playsync_manager.cc
- service/playsync_manager.hh
The SDK provides the following additional information to provide
the ability to integrate and manage screens and tts in your application.
```
// added dialog_id to the following functions:
ITTSListener::onTTSState(TTSState state,
const std::string& dialog_id)
ITTSListener::onTTSText(const std::string& text,
const std::string& dialog_id)
IDisplayListener::renderDisplay(const std::string& id,
const std::string& type,
const std::string& json,
const std::string& dialog_id)
```
The display interface is separated from the audio player interface.
> Add metadata for multi display handling

- examples/standalone/nugu_sample.cc
- examples/standalone/permission_listener.cc
- examples/standalone/permission_listener.hh
- include/interface/capability/capability_interface.hh
- include/interface/capability/permission_interface.hh
- service/capability/capability.cc
- service/capability/permission_agent.cc
- service/capability/permission_agent.hh
- service/capability_creator.cc
It add permission interface and agent for handling
directive and event about permission request.
If you receive RequestAccess directive, process permission
flow in application and update permission state.
Current permission states are included in context.
> add permission interface

- service/capability/audio_player_agent.cc
- service/capability/capability.cc
- service/capability/capability.hh
- service/capability/display_agent.cc
- service/capability/tts_agent.cc
- service/capability/tts_agent.hh
Because, the policy of managing playServiceId in playStack
is changed to use in playStackControl, it update related agents.
Target Agent : TTSAgent, AudioPlayerAgent, DisplayAgent
> apply playStackControl spec

- include/interface/capability/display_interface.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/playsync_manager.cc
- service/playsync_manager.hh
If user want to manage display rendering by self, it needs to
stop related play sync context hold timer. So, it provided
stopRenderingTimer method.
If user call stopRenderingTimer, it has to call displayCleared method
for notifying SDK that there are no more need to display rendering.
> display:add stopRenderingTimer

- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
Because, codes for UI and controlling sdk are mixed in nugu_sample,
it divide UI code from nugu_sample, and compose nugu_sample_manager.
> nugu_sample:divide UI code from nugu_sample

- include/core/nugu_equeue.h
- include/core/nugu_network_manager.h
- interface/nugu_client_impl.cc
- src/http2/http2_manage.h
- src/http2/v1_directives.cc
- src/nugu_equeue.c
- src/nugu_network_manager.c
equeue:
Add a queue for raising event callbacks with passing data from another thread to the thread context in which GMainloop runs.
Manage the queue thread-safely using GAsyncQueue and wakeup the GMainloop using eventfd.
> introduce a event-queue

- include/core/nugu_directive.h
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/capability.cc
- service/capability/capability.hh
- src/http2/v1_directives.cc
- src/nugu_directive.c
- tests/test-nugu-directive.c
1. capability: add refererrer dialog request id
- The refererrer dialog request id binds the user's actions.
2. network: add referrer_dialog_request_id to directive
- The referrer for dialogRequestId is added to directive spec.
So add related APIs to nugu_directive and network modules.
> Referrer Dialog Request ID

- examples/standalone/nugu_sample.cc
- include/core/nugu_network_manager.h
- include/interface/network_manager_interface.hh
- interface/network_manager_interface.cc
- interface/nugu_client_impl.cc
- interface/nugu_client_impl.hh
- service/network_manager.cc
- src/nugu_network_manager.c
Add a 'connecting' step to eliminate ambiguity in the network state.
> network: fix status callback

- include/core/nugu_network_manager.h
- service/capability/system_agent.cc
- service/network_manager.cc
- src/nugu_network_manager.c
When a handoff request is received, the client tries to connect to
another server while maintaining the current connection.
- If the handoff connection is successful, change the current
connection to the new server.
- If the handoff connection fails, disconnect all connections and
start over from the Registry step.
- If the handoff connection is lost, start again from the Registry
step.
> network: add handoff feature

- include/interface/capability/capability_interface.hh
- interface/nugu_client_impl.cc
- service/capability/capability.cc
- service/capability_creator.cc
- service/capability_creator.hh
Previously, for adding new CapabilityType and Agent,
it has to change 4 points in 3 sources.
So, As optimizing it, it reduce to change 2 points in 2 sources.
> optimize CapabilityType management

- examples/standalone/capability/system_listener.cc
- examples/standalone/capability/system_listener.hh
- examples/standalone/nugu_sample.cc
- include/interface/capability/capability_observer.hh
- include/interface/capability/system_interface.hh
- service/capability/system_agent.cc
Add system exception for handling common error. The application should
play the embedded TTS following the NUGU UX guide.
> System exception for common error

- src/network/dg_server.c
If is_end is true, the body of the attachment should be empty.
But, current dg_server_send_attachment() API always NULL check the data
parameter, therefore can't send the is_end=1 attachment.
> network: fix attachment bug in is_end=1 case

- interface/nugu_client_impl.cc
- plugins/gstreamer.c
This patch add following logs to debug initialization step
- Capability initialization
- GStreamer plugin - create ops of player driver
> add log for initializing step

- include/interface/capability/audio_player_interface.hh
- service/capability/audio_player_agent.cc
- service/capability/audio_player_agent.hh
- service/capability/display_agent.cc
- service/capability/display_agent.hh
- service/display_render_assembly.hh
- service/display_render_assembly.hpp
Between DisplayAgent and AudioPlayerAgent, because it needs
to handle display rendering infomation, almost same duplicated
codes exist both DisplayAgent and AudioPlayerAgent.
So, as adding DisplayRenderAssembly for handling display
rendering infomation, it remove duplication.
> update handling display render

- examples/standalone/nugu_sample.cc
- include/core/nugu_network_manager.h
- include/interface/network_manager_interface.hh
- include/interface/nugu_configuration.hh
- interface/nugu_configuration.cc
- service/network_manager.cc
- service/network_manager.hh
- src/network/dg_registry.c
- src/network/dg_server.c
- src/nugu_network_manager.c
- src/nugu_uuid.c
To clarify the role of the APIs, move the token API in the
configuration to the network manager.
> move token api to network manager

- service/capability/audio_player_agent.cc
- service/capability/display_agent.cc
- service/display_render_assembly.hh
- service/display_render_assembly.hpp
- service/playsync_manager.cc
- service/playsync_manager.hh
It change to compose DisplayRenderInfo in DisplayRenderAssembly.
And it apply const reference parameter on PlaySyncManager.
> update DisplayRenderAssembly efficiency

- CMakeLists.txt
- include/core/nugu_config.h
- include/core/nugu_network_manager.h
- include/interface/network_manager_interface.hh
- include/interface/nugu_configuration.hh
- interface/nugu_client_impl.cc
- interface/nugu_client_impl.hh
- interface/nugu_configuration.cc
- service/network_manager.cc
- service/network_manager.hh
- src/network/dg_registry.c
- src/network/dg_server.c
- src/network/http2/http2_network.c
- src/network/http2/v1_policies.cc
- src/nugu_network_manager.c
Move the USER_AGENT and REGISTRY_DNS configuration key to network
manager to clarify the role of the APIs.
> config: move UserAgent and RegistryDns to network

- interface/nugu_client_impl.cc
- service/audio_input_processor.cc
- service/audio_input_processor.hh
- service/audio_recorder_interface.hh
- service/audio_recorder_manager.cc
- service/audio_recorder_manager.hh
- service/speech_recognizer.cc
- service/wakeup_detector.cc
nugu recorder uses 50kbyte ring buffer memory by default.
SpeechRecognizer and WakeupDetector create  each nugu recorder,
and use memory inefficiently. The AudioRecorderManager manages
nugu recorders for efficient memory usage.
> Add AudioRecorderManager

- service/capability/system_agent.cc
- src/network/dg_server.c
- src/network/http2/v1_directives.cc
- src/network/http2/v1_directives.h
The payload specification of the HandoffConnection directive has
changed as follow:
- 'hostname' property changed to 'address'
- 'domain' property changed to 'hostname'
----
network: add connection timeout
add missing connection timeout to device gateway server to prevent
unlimit waiting for connection.
> capability: system agent handoff spec updated

- core/capability/system_agent.cc
- include/base/nugu_network_manager.h
- src/nugu_network_manager.c
To manage the 'Disconnect' event during handoff connection, split
the HANDOFF_SUCCESS event to HANDOFF_READY and HANDOFF_COMPLETED.
> network: split the handoff event

- core/audio_recorder_manager.cc
- core/capability/asr_agent.cc
- core/capability/audio_player_agent.cc
- core/capability/capability.cc
- core/capability_creator.hh
- core/capability_manager_helper.hh
- core/media_player.cc
- core/network_manager.cc
- core/playsync_manager.cc
It delete default constructor in CapabilityCreator and
CapabilityManagerHelper for preventing new instance,
because both class are static class.
It replace vector's push_back function to emplace_back
because later function reduce creating temporary instance
for parameter by one.
> upgrade using vector efficiency

- core/capability/asr_agent.cc
- core/capability/asr_agent.hh
- core/capability/audio_player_agent.cc
- core/capability/audio_player_agent.hh
- core/capability/system_agent.cc
- core/capability/tts_agent.cc
- core/capability/tts_agent.hh
- core/capability_manager.cc
- core/capability_manager.hh
- core/wakeup_handler.cc
- core/wakeup_handler.hh
- examples/standalone/capability/speech_operator.cc
- include/base/nugu_focus.h
- include/interface/wakeup_interface.hh
- src/nugu_focus.c
Removes focus processing on unnecessary MIC resources to counteract
external keyword detectors.
When using an external keyword detector, the application must be
responsible for and manage the state of the ASR.
> focus: remove MIC focus

- include/base/nugu_directive.h
- src/network/http2/http2_network.c
- src/network/http2/http2_request.c
- src/network/http2/http2_request.h
- src/network/http2/multipart_parser.c
- src/network/http2/multipart_parser.h
- src/nugu_directive.c
- src/nugu_directive_sequencer.c
- src/nugu_equeue.c
- src/nugu_network_manager.c
- tests/test-nugu-directive.c
Fix network related code to resolve memory leaks caused by abnormal situations.
- http2: add userdata to multipart parser
- http2: add destroy callback to request
- equeue: fix thread issue
- directive: apply ref count to fix memory leak
> Networkfix

- core/capability/asr_agent.cc
- core/capability/capability.hh
- core/wakeup_handler.hh
- examples/standalone/capability/display_listener.hh
- examples/standalone/capability/speech_operator.hh
- examples/standalone/capability/text_listener.hh
It remove redundant blank line in some class.
It remove virtual keyword in some class,
because that methods are already declared as override.
> fix code style

- include/base/nugu_equeue.h
- src/network/http2/http2_network.c
- src/network/http2/v1_directives.cc
- src/network/http2/v1_directives.h
- src/nugu_network_manager.c
Change 'g_idle_add' to 'equeue' so that it can be managed by
network_manager as a means to re-establish the long polling.
And, add exception handling for when the connection was finished
immediately on the server. In this case, try to connect to next
server without retrying.
> network: fix long polling re-establish logic

- core/capability/audio_player_agent.cc
- core/capability/display_agent.cc
- core/playsync_manager.cc
- core/playsync_manager.hh
It apply move semantics handling DisplayRenderer in PlaySyncManager
for removing temporary instance unnecessarily.
> upgrade efficiency

- src/nugu_equeue.c
add missing 'EXPORT_API' to equeue APIs to fix 'undefined reference..'
compile error message.
> base: add EXPORT_API to equeue

- plugins/gstreamer.c
Add gst_is_initialized() to check status of gstreamer. And also add
missing gst_deinit() to de-initialize the gstreamer.
> plugins: add init status check to gstreamer

- core/capability/audio_player_agent.cc
- core/capability/audio_player_agent.hh
- core/capability/capability.cc
- core/capability/capability.hh
- core/capability/tts_agent.cc
- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/display_listener.hh
- include/interface/capability/audio_player_interface.hh
- include/interface/capability/display_interface.hh
The AudioPlayer agent support content's lyrics and cache feature.
Application can control the content as setting shuffle, favorite and repeat.
Added audio chunk content to the specification, but will support it later.
> Update AudioPlayer v1.1

- CMakeLists.txt
- packaging/bionic/rules
- packaging/xenial/rules
When building Debian packaging, disable AddressSanitizer to remove
asan dependencies on building user applications.
> build: disable asan on debian packaging

- core/capability/tts_agent.cc
- include/base/nugu_uuid.h
- src/network/dg_server.c
- src/nugu_event.c
- src/nugu_uuid.c
- tests/CMakeLists.txt
- tests/test-nugu-uuid.c
NUGU UUID spec is updated to v2.
```
/-------------------------------\
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
|===================+===+=======|
|      time(5)      | v |       ~
|---------------+---+---+-------|
~  hash(6)      |   random(4)   |
\---------------+---------------/
```
* 5 bytes: time(GMT): EPOCH milliseconds - 1546300800000
* 1 bytes: version: 0x1
* 6 bytes: hash: cut(sha1(token) 20 bytes, 0, 6 bytes)
* 4 bytes: random
> base: apply uuid v2 spec

- clientkit/nugu_client.cc
- clientkit/nugu_client_impl.cc
- clientkit/nugu_client_impl.hh
- core/capability/asr_agent.cc
- core/capability/asr_agent.hh
- core/capability/audio_player_agent.cc
- core/capability/audio_player_agent.hh
- core/capability/capability.cc
- core/capability/capability.hh
- core/capability/delegation_agent.cc
- core/capability/display_agent.cc
- core/capability/extension_agent.cc
- core/capability/location_agent.cc
- core/capability/mic_agent.cc
- core/capability/system_agent.cc
- core/capability/system_agent.hh
- core/capability/text_agent.cc
- core/capability/text_agent.hh
- core/capability/tts_agent.cc
- core/capability_creator.cc
- core/capability_creator.hh
- core/capability_manager.cc
- core/capability_manager.hh
- core/display_render_assembly.hpp
- core/playsync_manager.cc
- core/playsync_manager.hh
- core/wakeup_handler.cc
- examples/standalone/nugu_sample.cc
- include/clientkit/nugu_client.hh
- include/interface/capability/capability_interface.hh
It remove CapabilityType enum for improving expansibility
of CapabilityAgents. Instead, it recognize each CapabilityAgent
by string.
Be careful. Each Capability Name is case sensitive, so you have
to write spelling correctly as being defined in NDI.
> remove CapabilityType

- CMakeLists.txt
- src/CMakeLists.txt
Fix build scripts to remove warnings on clang-tidy.
> build: fix warnings on clang-tidy

- examples/standalone/nugu_sample.cc
- include/clientkit/nugu_client.hh
- include/interface/capability/capability_observer.hh
- src/clientkit/nugu_client.cc
- src/core/capability/capability.cc
It remove each capability handler's getter from NuguClient
for removing depedency.
Instead, it's possible to get capability handler's instance
by calling getCapabilityHandler as argument to handler's instance.
> remove each capability handler getter

- examples/standalone/nugu_sample.cc
- include/capability/capability_interface.hh
- include/clientkit/nugu_client.hh
- include/clientkit/nugu_core_container_interface.hh
- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/capability.cc
- src/capability/capability.hh
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- src/core/speech_recognizer.hh
It apply INuguCoreContainer interface to ICapabiltyInterface
for using NuguCoreContainer's functions like creating
SpeechRecoginzer or MediaPlayer.
Because each CapabilityAgent inherit ICapbilityInterface,
they has NuguCoreContainer instance basically.
(That instance is added by NuguClient default.)
> Apply INuguCoreContainer to CapabilityAgent

- src/core/playsync_manager.hh
The structure does not have an initial pointer value.
This causes an application crash.
> fix the hangup issue.

- include/clientkit/capability_helper_interface.hh
- include/clientkit/nugu_core_container_interface.hh
- include/clientkit/playsync_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/capability.cc
- src/capability/capability.hh
- src/capability/delegation_agent.cc
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/display_render_assembly.hh
- src/capability/display_render_assembly.hpp
- src/capability/extension_agent.cc
- src/capability/mic_agent.cc
- src/capability/system_agent.cc
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It add CapabilityHelper which encapsulate CapabilityManager.
It is composed by methods which current CapabilityAgents required.
Also it's possible to get PlaySyncManager instance from CapabilityHelper.
(Its implementation is hidden in NuguCore, but we can access
from IPlaySyncManager interface).
> add CapabilityHelper for handling NuguCore

- src/base/network/dg_server.c
- src/base/network/http2/v1_event_attachment.c
Fixed a bug in which close_data was not called when the data size is 0
(e.g. is_end=true with attachment data).
> network: fix missing close_data bug

- include/base/nugu_event.h
- src/base/nugu_event.c
- src/capability/asr_agent.cc
- src/capability/capability.cc
- src/capability/capability.hh
Add a type to distinguish between json only event and events with
attachment data in addition to json.
> base: add type to nugu_event

- include/capability/asr_interface.hh
- include/capability/audio_player_interface.hh
- include/capability/capability_factory.hh
- include/capability/delegation_interface.hh
- include/capability/display_interface.hh
- include/capability/extension_interface.hh
- include/capability/location_interface.hh
- include/capability/mic_interface.hh
- include/capability/speaker_interface.hh
- include/capability/system_interface.hh
- include/capability/text_interface.hh
- include/capability/tts_interface.hh
- include/clientkit/capability_interface.hh
- include/clientkit/capability_observer.hh
- include/clientkit/nugu_client.hh
- include/clientkit/nugu_client_listener.hh
- src/capability/audio_player_agent.hh
- src/capability/capability.hh
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_manager.hh
- src/core/capability_manager_helper.hh
- src/core/media_player.hh
- src/core/playsync_manager.hh
Because ICapabilityInterface which is the most base class
of All CapabilityAgents has located in NuguCapability namespace,
NuguSample, NuguClientKit, NuguCore all has dependent it.
As it's not appropriate, change namespace to NuguClientKit
for reducing dependency, and increasing usage.
> change capability_interface namespace

- CMakeLists.txt
- include/base/nugu_network_manager.h
- src/base/CMakeLists.txt
- src/base/network/dg_server.c
- src/base/network/dg_server.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/v1_events.c
- src/base/network/http2/v1_events.h
- src/base/nugu_log.c
- src/base/nugu_network_manager.c
- src/capability/asr_agent.cc
- src/capability/capability.cc
- src/capability/capability.hh
add POST to /v1/events API to support multipart based event.
There are 2 ways to send the event to server
- /v1/event (json) with /v1/event-attachment (binary)
- /v1/events (multipart)
The default option is /v1/event with /v1/event-attachment. But, it
can be changed by setting the environment variable below.
$ export NUGU_NETWORK_USE_EVENTS=1
> network: add /v1/events API support

- examples/standalone/capability/speaker_listener.cc
- examples/standalone/capability/speaker_listener.hh
- examples/standalone/nugu_sample.cc
- include/capability/capability_factory.hh
- include/clientkit/nugu_client.hh
- src/capability/capability_factory.cc
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
It change the method of adding capability which get only
capability instance to parameter. So, if you want to set
related listener or set attribute, you have to set before
adding to NuguClient.
ex)
ISystemHandle* system = CapabilityFactory::makeCapability<SystemAgent, ISystemHandler>();
NuguClient nugu_client = new NuguClient();
nugu_client->getCapabilityBuilder()
->add(system)
->construct();
> change method to add capability

- include/base/nugu_uuid.h
- src/base/network/http2/v1_events.c
- src/base/nugu_uuid.c
Fix the pre-defined boundary to random boundary.
> network: fix to use random boundary for /v1/events

- examples/CMakeLists.txt
- examples/capability_injection/CMakeLists.txt
- examples/capability_injection/battery_agent.cc
- examples/capability_injection/battery_agent.hh
- examples/capability_injection/main_capability_injection.cc
It add capability agent injection example.
The target example is BatteryAgent. From that,
you can check a context about battery level is extracted.
> add capability injection example

- examples/simple_asr/main_asr.cc
- examples/simple_text/main_text.cc
- examples/standalone/nugu_sample.cc
- include/capability/capability_factory.hh
- src/capability/capability_factory.cc
It update to set each capability listener by parameter
when calling CapabilityFactory::makeCapability() method
for improving convenience.
> update setting capability listener

- examples/capability_injection/battery_agent.cc
- examples/capability_injection/battery_agent.hh
- examples/capability_injection/main_capability_injection.cc
- examples/simple_asr/main_asr.cc
- examples/simple_text/main_text.cc
- examples/standalone/nugu_sample.cc
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/capability.cc
- src/capability/capability.hh
- src/capability/system_agent.cc
- src/capability/system_agent.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/nugu_client_impl.cc
In previously, NuguClient had charge of capability instance
management, so, when deinitializing NuguClient, it removed
that instances.
As moving the role of managing capability instance to Application,
it add deinitialize method in capability interface for clearing
relevant resources which is needed to do before removing instance.
When deinitializing NuguClient, that added method is called, so
the Application may remove capability instance freely.
> Move role capability instance management

- examples/standalone/nugu_sample.cc
- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
As the application manages capability instance,
NuguClient does not need to provide capability handler getter.
So, that method is removed.
> Remove capability handler getter

- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_events.c
After passing the result of the event transmission to the equeue,
the code can access the memory that has already been released due to
timing issues.
> base: fix heap-use-after-free bug

- src/capability/audio_player_agent.cc
When a service changes, the service and the event do not match.
> AudioPlayerAgent: Sync event with Play service

- include/base/nugu_log.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v1_directives.cc
- src/base/network/http2/v1_event_attachment.c
- src/base/network/http2/v1_policies.cc
- src/base/nugu_log.c
- src/base/nugu_network_manager.c
Added protocol log messages for more convenient log analysis. And the
hexdump has also been enhanced for network level log analysis.
Usage:
export NUGU_LOG_LEVEL=default,network_trace,protocol
or
export NUGU_LOG_LEVEL=protocol
or
export NUGU_LOG_LEVEL=all
> base: add protocol log support

- tests/core-timer/nugu_timer_mock.cc
- tests/core-timer/test-core-NuguTimer.cc
Fix build error for following error message
error: missing sentinel in function call
> tests: fix build error on allwinner target

- src/capability/asr_agent.cc
- src/capability/system_agent.cc
- src/capability/system_agent.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
ASRAgent occupy the speaker's focus until the directives will be
arrived as "TTS.Speak" or "AudioPlayer.Play". In certain services,
there is a case where there is no corresponding directives
in the utterance response, and a focus release issue occurs.
> Focus: release asr focus

- include/capability/asr_interface.hh
- include/capability/text_interface.hh
- include/capability/tts_interface.hh
- src/capability/asr_agent.cc
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
The ASR,TTS,Text Agent need attibutes for activating.
Even the setter about attribute is provided, cause default
values exist in sdk privately, the user never know that value.
So, it update to show each agent's default value in
related interface header file.
> Open Capability Default Attribute Value

- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
In previously, the Application is possible to create and
delete CapabilityBuilder directly, not through NuguClient.
It's not recommend usage, so, it adjust accessibility
to prevent to create/delete that instance directly.
Instead, the CapabilityBuilder instance is
only provided by NuguClient.
> Adjust CapabilityBuilder accessibility

- include/base/nugu_directive_sequencer.h
- src/base/nugu_directive_sequencer.c
- src/core/capability_manager.cc
The directive sequencer originally borrowed the concept of hooks to
register and process multiple callbacks.
However, since there is no need at the moment, so change it to handle
only one callback simply.
> base: fix directive sequencer callback concept

- examples/standalone/capability/system_listener.cc
- examples/standalone/capability/system_listener.hh
- include/capability/system_interface.hh
- src/capability/system_agent.cc
Device battery information is managed separately in the new
capability interface as Battery Interface.
> SystemAgent: Remove context info

- examples/oob_setup/README.md
- examples/oob_setup/nugu_oob_server.py
The authentication server now supports 'localhost' host name.
Therefore, change the 'lvh.me' to 'localhost'.
> examples: change lvh.me to localhost

- include/clientkit/playsync_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It apply the recent play context maintain policy.
- hold context about 10m' when AudioPlayer is paused by directive.
> Apply recent play context policy

- src/base/nugu_recorder.c
- src/core/audio_input_processor.cc
- src/core/audio_recorder_manager.cc
Recorder manages ringbuffer and AudioRecorderManager manages
the recorder list via mutex for multi-threaded support.
Fix the issue #174
> Recorder: modify the mutex

- examples/standalone/capability/speaker_listener.cc
- examples/standalone/capability/speaker_listener.hh
- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
The application tells the NUGU SDK which volume and mute has been
changed with the button. When an application receives a volume
change request from the NUGU SDK, it must control the volume and
ask the NUGU SDK to send a control result event to the server.
> SpeakerAgent: update api

- examples/capability_injection/battery_agent.cc
- examples/capability_injection/battery_agent.hh
- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
In some case, because it needs to suspend all current
capability actions, it add suspend and restore function
in ICapabilityInterface.
There don't need to override above methods in all capability.
> add capabilty suspend,restore

- CMakeLists.txt
- plugins/CMakeLists.txt
Fix the build script to make configurable the NUGU plugin to be
included in the build through the build options.
In addition, GStreamer library does not support dynamic loading,
so it is forced to link to the NUGU SDK when enable the NUGU
GStreamer plugin.
> build: add build options to plugins

- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
In nugu sample, it add cli commands for testing
suspending/restoring capability actions.
It would implements the required action in each capability.
> add suspend/restore command in nugu sample

- include/base/nugu_log.h
- src/base/nugu_log.c
The nugu_log_get_system() API is missing in the log API.
> base: add missing get_system() to log api

- plugins/gstreamer.c
Remove the 'gst_deinit()' call in the unload callback of sdk
gstreamer plugin because the API is only for debugging purpose.
> plugin: remove gst_deinit in gstreamer plugin

- src/clientkit/nugu_client_impl.cc
Fix the destroyInstance to destoryAudioRecorderManager to correct API
pair.
> clientkit: fix invalid destroy function

- include/clientkit/playsync_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/text_agent.cc
- src/core/capability_manager.cc
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It update to reset context hold timer
when asr failed.
It update to hold media pause timer when user
is doing some action. If the action is completed,
it restart context hold timer.
> update play context policy

- examples/capability_injection/battery_agent.cc
- examples/capability_injection/battery_agent.hh
- examples/standalone/nugu_sample.cc
- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
It implements suspend, restore methods in capability agents
which are required.
In ASRAgent, it implements suspend() for stopRecognition.
In TTSAgent, it implements suspend() for stopTTS.
In AudioPlayerAgent, it implements suspend() for pause/stop
and restore() for resume.
Also, it apply suspend policy which is possible to select
pause or resume action in each capability agent.
> Implements capability suspend/restore

- examples/standalone/nugu_sample.cc
- src/capability/tts_agent.cc
It update to suspend TTSAgent from stopTTS to releaseFocus,
because, it needs to remove play context simultaneously.
And, it change SuspendPolicy of AudioPlayerAgent to default,
because, it seems right to customize policy in required application.
> update TTSAgent suspend

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
During the ASR has focus as startListening, if AudioPlayer
directive is sended to client, it steal focus from ASR.
As a result, ASR is stopped abnormally.
So, it fix to allow to steal ASR focus only ListenigState is done.
> fix ASR stop unexpected issue

- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/delegation_agent.cc
- src/capability/delegation_agent.hh
- src/capability/extension_agent.cc
- src/capability/extension_agent.hh
- src/capability/mic_agent.cc
- src/capability/mic_agent.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/capability/system_agent.cc
- src/capability/system_agent.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
Depending on the network connection status and server status,
event transmission may cause an error, and it should be able to
control it. CapabilityManager collects the event's result
from network manager and forward them to each CapabilityAgent.
> Event result callback

- examples/standalone/nugu_sample_manager.cc
- src/core/audio_recorder_manager.hh
fix the warning reported by clang-tidy.
> Remove Warning

- include/base/nugu_network_manager.h
- src/base/nugu_network_manager.c
Add notify callback for event transmission to use for event sending
status monitoring. (e.g. log sender)
> network: add notify callback for event send

- examples/standalone/nugu_sample.cc
- include/clientkit/capability_helper_interface.hh
- include/clientkit/network_manager_interface.hh
- src/clientkit/network_manager_interface.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/network_manager.cc
The application can know the events sent by the NUGU SDK and
the result of the sent events through the network manager listener.
> NetworkManager: Event Send/Result Listener

- src/base/network/http2/directives_parser.cc
- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v1_directives.c
- src/base/network/http2/v1_events.c
Move the request resume API to http2_network module to resolve thread
issue. (curl_easy_pause is not thread safety)
> network: fix request resume bug

- include/capability/asr_interface.hh
- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
It add the method which is possible to get
epd silence interval (frankly, it's epd pause length).
Because, it's related to ASR, that method is added to ASRAgent.
Be careful, not to use that method before NuguClient initialized.
The reason is at that time, the required instance(SpeechRecognizer)
is not created, we can't retrieve correct value.
> add method about EpdSilenceInterval

- src/base/nugu_network_manager.c
EXPORT_API prefix is missing in some network APIs.
> network: add missing EXPORT_API

- src/clientkit/nugu_client_impl.cc
If the plugin fails to load at client initialization, treat it as
success. This is because some systems don't have plug-ins.
> clientkit: ignore the plugin loading result

- externals/0003_curl_ca_variables.patch
Update the curl library version v7.67.0 to v7.69.1
- Changelog: https://curl.haxx.se/changes.html
SDK Releated changes
- curl_easy_pause() improved
- cmake script updated
- conn, multi, http2 improved
> externals: update curl to v7.69.1

- externals/0004_tizen_ca_bundle_path.patch
- externals/patch_curl.sh
Add tizen CA bundle path patch to curl build.
> externals: add tizen ca path patch to curl

- CMakeLists.txt
- include/base/nugu_log.h
- src/base/nugu_log.c
Add build option for log message ansicolor to support text only log
message system.
> build: add log message ansicolor option

- include/base/nugu_pcm.h
- plugins/portaudio.c
- src/base/nugu_pcm.c
NuguPcm now supports providing audio information such as
playback position and duration.
> Pcm: Add get_position and get_duration

- src/base/nugu_pcm.c
When calling 'nugu_pcm_start' function, userdata is not clearly
freed by calling 'nugu_pcm_set_userdata (pcm, NULL)'. Because of
this, Portaudio still uses the old value.
> Pcm: fix the heap-use-after-free

- CMakeLists.txt
Change linking order for asan to fix following error:
ASan runtime does not come first in initial library list;
you should either link runtime to your application or manually
preload it with LD_PRELOAD
> build: fix asan link order

- include/base/nugu_focus.h
- src/base/nugu_focus.c
- src/capability/asr_agent.cc
- src/capability/tts_agent.cc
Alert is changed highest priority and remove unused type.
> Focus: modify focus priority

- plugins/filedump.c
- src/base/nugu_pcm.c
There is missing callback invocation for push_data in the
push_data_done function.
> base: add missing push_data call to push_data_done

- src/core/audio_input_processor.cc
g_main_context_invoke() cause deadlock in some targets.
(gmainloop integrated ecore loop)
So change to g_idle_add().
> core: fix sync_event

- include/capability/system_interface.hh
- src/capability/system_agent.cc
- src/capability/system_agent.hh
The 'Disconnect' event is deprecated in the V2 API.
> capability: remove 'Disconnect' from SystemAgent

- src/clientkit/capability.cc
Check and call the event result callback is exist or not.
> Capability: fix the hang-up issue.

- include/base/nugu_network_manager.h
- src/base/network/http2/v1_policies.cc
- src/capability/system_agent.cc
The 'address' field is deprecated from the server policy object.
Only 'hostname' and 'port' fields are used to connect to server.
> network: remove 'address' filed from policy

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
The AudioPlayerAgent supports to request play contents
in third party application now. For example, you can play
specific music with a NUGU device in the NUGU mobile app.
> AudioPlayerAgent: Update version 1.2

- src/capability/asr_agent.cc
- src/capability/text_agent.cc
- src/capability/text_agent.hh
TextAgent: Update specification
Add the asr context information to the context in event(TextInput).
The event(sendEventTextSourceFailed) is removed in specification.
> TextAgent: Update specification

- src/core/audio_recorder_manager.cc
Even though the recorder was already started and used, there was
a bug that could cause the recorder to start over and fixed it.
> AudioRecorderManager: Fix a bug

- src/capability/text_agent.cc
The commit modified in #246 was applied to the Text Interface 1.1.
> TextAgent: Update version 1.1

- include/capability/asr_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/speech_recognizer.cc
- src/core/wakeup_detector.cc
- src/core/wakeup_handler.cc
When timeout and fail occurred during Recognition, there was a bug
in which the state was changed first and the event was changed,
and this was fixed.
> ASRAgent: Fix status and event occurrence

- include/clientkit/capability.hh
- src/capability/audio_player_agent.cc
- src/clientkit/capability.cc
Capability manages RequestDialogId of corresponding Directive
for each Event as RDRID.
Apply the RDRID #251 to AudioPlayerAgent.
> Capability: Modify for RDRID #251

- include/clientkit/media_player_interface.hh
add missing virtual destructor interface for MediaPlayerListener
> clientkit: add missing destructor for listener

- examples/standalone/capability/speech_operator.cc
- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/audio_input_processor.cc
- src/core/audio_input_processor.hh
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
- src/core/wakeup_handler.hh
StartRecognition does not work normally when stopRecognition
and startRecognition are repeated continuously #250. StartWakeup is
also similar. To solve this problem, added the ID to request listening
and checked the ID when receiving event.
> ASR, KWD: Fix the multi-thread issue

- src/core/audio_input_processor.cc
Crash on certain platforms when using std::condition_variable.
> Thread: fix the hangup issue

- src/base/network/dg_server.c
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
The message-id header is required from latest API spec.
> network: add message-id to /v2/events attachment

- include/base/nugu_log.h
- src/base/nugu_log.c
The 'stderr' standard output was provided as a log system to
separate from printf output, but 'stdout' was also added to be
selectable if necessary.
Usage:
$ export NUGU_LOG=stdout
or
nugu_log_set_system(NUGU_LOG_SYSTEM_STDOUT)
> base: add stdout to log system

- src/core/media_player.cc
- src/core/media_player.hh
There is a bug where the playback position is always filled
with a value of 0 in `AudioPlayer.PlaybackStarted` even if
`AudioPlayer.Play` has an `offsetInMilliseconds` value.
> Audioplayer: Fix the playback position bug

- src/capability/asr_agent.cc
When asr has focus in expecting speech, it reset
expecting speech state, so, it cannot send that info to server.
So, it fix not to reset expecting speech state,
when asr has on focus.
> fix asr expecting speech bug

- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
Add a callback for the completion of transmission of all request data.
> network: add send complete callback to request

- src/clientkit/capability.cc
To make log analysis easier, changed the log message for the event
result where the event callback is not registered.
as is: The message-id is missing.
receive ASR.Recognize({msg-id}) result 1(code:200)
The ASRAgent ignore the StopRecognize result 1(code:200)
to be:
receive ASR.Recognize({msg-id}) result 1(code:200)
receive ASR.StopRecognize({msg-id}) result 1(code:200) - ignored
> clientkit: change log message for event result

- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v2_events.c
Add response code callback to emit the http2 request result to
application quickly.
> network: add response code callback

- src/capability/asr_agent.cc
Fix the miss matched context information.
> ASRAgent: Fix the bug

- examples/standalone/capability/text_listener.cc
- examples/standalone/capability/text_listener.hh
- include/capability/text_interface.hh
- src/capability/text_agent.cc
It update TextAgent which is possible to handle text command
by application.
If the application return true, when calling handleTextCommand(),
the sdk does not process that directive anymore.
> update TextAgent for handling text by application

- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
Add libcurl error code to http2_request result to identify error
condition such as DNS error.
> network: add libcurl error code to http2_request

- src/base/network/http2/v2_events.c
The network does not have enough time to send events and wait for
the directive. The problem occurs when the server response is delayed.
> Network: increase the timeout

- examples/standalone/nugu_sample.cc
- include/base/nugu_log.h
- include/base/nugu_prof.h
- include/base/nugu_uuid.h
- src/base/network/dg_server.c
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v2_events.c
- src/base/nugu_log.c
- src/base/nugu_prof.c
- src/clientkit/nugu_client_impl.cc
The profiling module provides notification and performance measurement
for each condition.
When 'nugu_prof_mark()' or 'nugu_prof_mark_data()' is called, the
timestamp and additional data are stored in the internal cache, and
events can be received through callbacks.
Developers can fetch and analyze the profiled data at the moment they
want through a callback or 'nugu_prof_get_last_data()' API.
In addition, it is possible to simply output the profiling result of
a specific range through the 'nugu_prof_dump()' API.
e.g.
--------------------------
Profiling: 0(Created) ~ 38(END)
[ 0]          Created: <date.msec>   0 msec
[ 1]      Plugin init: <date.msec>  11 msec [ 0 ~  1]:  11 msec
[ 2]      Plugin done: <date.msec> 114 msec [ 1 ~  2]: 102 msec
[ 3]      Initialized: <date.msec> 120 msec …
> base: introduce profiling feature

- plugins/gstreamer.c
The audio source is not changed if the player calls as belows:
> 1. nugu_player_stop()
> 2. nugu_player_set_source()
> 3. nugu_player_resume()
> Gstreamer: Fix the bug

- src/capability/audio_player_agent.cc
When `AudioPlayer.Stop` is received, `AudioPlayer.PlaybackPaused`
is sent before sending `AudioPlayer.PlaybackStopped`, causing a bug.
> AudioPlayer: fix the bug

- src/capability/audio_player_agent.cc
- src/core/tts_player.cc
- src/core/tts_player.hh
Integration of AudioPlayerAgent's attachment media is complete.
Therefore, it removes the temporary code.
> AudioPlayerAgent: Remove temporary code

- include/base/nugu_focus.h
- include/clientkit/playsync_manager_interface.hh
- src/base/nugu_focus.c
- src/capability/tts_agent.cc
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It add NUGU_FOCUS_TYPE_CALL type to nugu_focus for handling
focus about NuguCall Interface.
It update PlaySyncManager which is possible to retrieve
PlaysyncLayer Type about play service id.
- PlaysyncLayer Type : Info, Media, Alert, Call.
> Update to handle Call focus

- src/core/playsync_manager.cc
It update to refresh PlaysyncLayer when try to
add context stack's element.
It change nugu log level from nugu_error to nugu_warn
about out_of_range exception case.
> Update to refresh PlaysyncLayer

- include/clientkit/playsync_manager_interface.hh
- src/capability/asr_agent.cc
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It change context hold policy in DM mode which to maintain
during DM listening time.
It remove context immediately after ending call,
even if the finish TTS has exist.
> Apply changed context maintenance policy

- examples/standalone/capability/tts_listener.cc
- include/base/nugu_prof.h
- src/base/nugu_prof.c
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
Fix the TTS start/finish profiling point to the point at which the event
is sent. And add the point that received the TTS speak directive.
> profiling: fix TTS profiling point

- src/core/media_player.cc
There is a mismatch in the player's volume setting.
1. Default volume of MediaPlayer is NUGU_SET_VOLUME_MAX(100).
media_player.hh line 32:
explicit MediaPlayer(int volume = NUGU_SET_VOLUME_MAX);
2. Default volume of nugu_player is NUGU_SET_VOLUME_DEFAULT(50).
nugu_player.c line 177:
player->volume = NUGU_SET_VOLUME_DEFAULT;
As a result, unlike the intention, the volume is always set to
NUGU_SET_VOLUME_DEFAULT(50).
This patch add the setVolume() API call to correct above mismatch
issue.
> core: fix media player default volume setting

- include/base/nugu_prof.h
- src/base/network/dg_server.c
- src/base/network/dg_types.h
- src/base/network/http2/directives_parser.cc
- src/base/network/http2/directives_parser.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/v1_directives.c
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
- src/base/nugu_network_manager.c
- src/base/nugu_prof.c
Add directive profiling for both event-response and server-initiative
points. And also add timeout for response directive data.
> base: fix network profiling

- examples/standalone/capability/tts_listener.cc
- examples/standalone/capability/tts_listener.hh
It upgrade displaying TTS text on cli log.
It apply to replace {W} tag to wakeup word,
if such tag exist in tts text.
> Upgrade TTS Text Display

- src/capability/mic_agent.cc
Temporary and exceptionally lowercase values is allowed.
> Mic: lowercase values

- plugins/gstreamer.c
Use the `gh->last_state` variable instead of using
`gst_element_get_state` function.
> Gstreamer: remove unnecessary code

- examples/standalone/capability_collection.cc
- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It change to use unique pointer about managing SpeakerType
and apply const reference parameters at methods
which are using map of SpeakerType.
Also, it work in PlaysyncManager too.
> Change use to smart pointer

- include/base/nugu_focus.h
- src/base/nugu_focus.c
Add MEDIA_LOCK focus to enable media control manually in the
application.
The application can control the playback of the current media
through get or release for MEDIA_LOCK focus.
> focus: add MEDIA_LOCK focus

- src/base/network/http2/directives_parser.cc
- src/base/network/http2/directives_parser.h
- src/base/network/http2/multipart_parser.c
- src/base/network/http2/multipart_parser.h
- src/base/network/http2/v1_directives.c
- src/base/network/http2/v2_events.c
add directive and multipart end-boundary(`--{boundary}--`) detect
callback to multipart parser.
> network: add directive parser callback

- examples/standalone/nugu_sample.cc
- include/base/nugu_plugin.h
- include/clientkit/nugu_client.hh
- src/base/nugu_plugin.c
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
Add `loadPlugins()` API to client kit to distinguish Capability
initialization and Plugin initialization.
This API can be omitted. Therefore, if `initialize()` is called
without calling `loadPlugins()` first, the `loadPlugins()` is
automatically called using the default directory by `initialize()`.
> clientkit: add loadPlugins() API

- include/clientkit/capability.hh
- plugins/gstreamer.c
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
There is a bug in audio focus and playeback when suspending
and restoring agents.
> Capability: fix the suspend/restore issue

- src/capability/audio_player_agent.cc
If the application requested suspend with SuspendPolicy::STOP,
AudioplayerAgent will not play media until the application
requests restore.
> AudioPlayerAgent: Suspend action

- plugins/gstreamer.c
There is a bug that plays content when buffering is complete
even if the player requests to pause while loading media content.
> Gstreamer: fix the bug.

- src/capability/tts_agent.cc
The NUGU SDK provides the function to stop the NUGU service when
the user speeches '그만' while the TTS is playing.
> TTSAgent: Update version 1.1

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- src/clientkit/capability.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
It add notifyEventResponse() method in Capability
for receiving response info about sent event.
(It composed by message_id, raw json and whether success.)
If the CapabilityAgent need to do something with above method,
it has to override it in that agent.
> Capability:add method for receiving event response

- include/clientkit/capability.hh
- src/clientkit/capability.cc
As the parseEventResultDesc method is not used in publicly,
it change to declare in Impl for preventing access by outer.
> Capability:hide parseEventResultDesc to private

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
During media playback, the `PlaybackStarted` event is not sent
on the next media playback request from the App Control Center.
> AudioPlayer: Fix the bug.

- src/base/network/http2/v1_policies.cc
There is missing NUL check for nugu_buffer data.
So use std::string with specific size instead of direct casting to 'char *' type.
> network: fix NUL check bug in the response data

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Add the event `RequestCommandFailed` for Media Control Center
and the reason field in the event `PlaybackStopped` for PlayRouter.
> AudioPlayerAgent: Update version 1.3

- src/core/capability_manager.cc
The 'os' field has been added to the 'client' json object.
The value of the above key can be one of 'iOS', 'Android', and 'Linux'.
> core: add os info to client part

- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
As the network policy is changed not to send SynchronizeState event
when the connection is completed, it remove INetworkManagerListener
inheritance and remove overridden onStatusChanged method.
> NuguClient:Remove INetworkManagerListener inheritance

- include/base/nugu_pcm.h
- plugins/filedump.c
- plugins/portaudio.c
- src/base/nugu_pcm.c
- src/core/tts_player.cc
- tests/test-nugu-pcm.c
add .create and .destroy ops callbacks to pcm driver to split OpenStream
and StartStream in the PortAudio plugin.
> pcm: add create/destroy ops to pcm driver

- include/base/nugu_directive.h
- include/base/nugu_directive_sequencer.h
- include/base/nugu_network_manager.h
- src/base/nugu_directive.c
- src/base/nugu_directive_sequencer.c
- src/base/nugu_network_manager.c
- src/clientkit/nugu_client_impl.cc
For future refactoring, remove the directive sequencer dependency from
the network manager module.
> base: remove dirseq dependency from networkmanager

- examples/standalone/nugu_sample.cc
- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/focus_manager_interface.hh
- include/clientkit/nugu_client.hh
- include/clientkit/nugu_core_container_interface.hh
- src/clientkit/capability.cc
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- tests/core/CMakeLists.txt
- tests/core/test-core-focus-manager.cc
FocusManager replaces NuguFocus by extending the following features:
* Supports freely generate and inject focus channel
* Supports easily control for changing state of focus channel
* Supports monitoring of changing state of focus channel
* Remove internally hard-coded focus name and priority
> Focus: Add FocusManager

- include/base/nugu_decoder.h
- include/base/nugu_pcm.h
- include/base/nugu_player.h
- include/base/nugu_recorder.h
- plugins/filedump.c
- plugins/gstreamer.c
- plugins/opus.c
- plugins/portaudio.c
- src/base/nugu_decoder.c
- src/base/nugu_pcm.c
- src/base/nugu_player.c
- src/base/nugu_recorder.c
- tests/test-nugu-decoder.c
- tests/test-nugu-player.c
Some of the drivers' custom data configuration APIs are not unified,
so they have been modified as follows:
int nugu_XXX_set_driver_data(XXX *xxx, void *data);
void *nugu_XXX_get_driver_data(XXX *xxx);
So if the driver needs to store or load the device handle in an object,
please use the above API.
> base: fix driver custom data API naming

- src/capability/text_agent.cc
A Session interface for managing conversation sessions has been added
to remove the session id from TextAgent.
> TextAgent: Update version 1.2

- src/capability/asr_agent.cc
Because, the version of ASR Interface 1.2 which deprecated sessionId
is changed to 1.3, it update CAPABILITY_VERSION of ASRAgent too.
> ASR:Update ASR Interface version

- include/clientkit/focus_manager_interface.hh
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test-core-focus-manager.cc
Add a `name` parameter to `releaseFocus` function for explicit
control focus.
> FocusManager: releaseFocus

- include/clientkit/session_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/session_agent.cc
- src/core/session_manager.cc
- src/core/session_manager.hh
As following the agreement of common naming about SessionManager,
it changes the below function name.
sync() -> activate()
release() -> deactivate()
getSyncedSessionInfo() -> getActiveSessionInfo()
> Session:Change function name in SessionManager

- plugins/portaudio.c
Use of memory after it is freed
> Portaudio: Fix the bug

- include/clientkit/capability_helper_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/text_agent.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
It change the location of releasing the ASR focus from CapabilityManager
to ASRAgent when there are no existing stealable directive namespace
like TTS, AudioPlayer.
> ASR:update ASR focus release

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- include/clientkit/network_manager_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/clientkit/capability.cc
- src/clientkit/network_manager_interface.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
When an sending event response failure such as a timeout, the payload
is filled with nullptr, and assigning it to std::string causes hangup.
> Capability: Fix the hangup

- include/base/nugu_directive_sequencer.h
- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/directive_sequencer_interface.hh
- include/clientkit/nugu_core_container_interface.hh
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
- tests/core/CMakeLists.txt
- tests/core/test-core-directive-sequencer.cc
The DirectiveSequencer delivers the directives received from the
network to the CapabilityAgent according to the dialog-id and
blocking policy.
Each Capability agent must register blocking policies through
DirectPolicySequencer::addPolicy() to handle the Directive in
accordance with the policy.
In addition, listeners must be registered to receive directive
events from the DirectiveSequencer.
> core: introduce a new DirectiveSequencer

- src/core/session_manager.cc
- src/core/session_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test-core-session-manager.cc
It add test for SessionManager.
It add the getAllSessions() in SessionManager
for getting all session objects.
> test:add SessionManager test

- src/core/capability_manager.cc
- src/core/capability_manager.hh
It apply the initialization list when creating instance of manager.
It apply the const reference when handling loop items.
It commonize makeAllContextInfo and makeAllContextInfoStack.
It apply emplacement when inserting item to map container.
> CapabilityManager: Optimize Code

- examples/standalone/capability_collection.cc
- include/capability/speaker_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
The speaker type is added as below.
* NUGU
* MUSIC
* RINGTON
* CALL
* NOTIFICATION
* ALARM
* VOICE_COMMAND
* NAVIGATION
* SYSTEM_SOUND
The agent with the player sets the volume value through SpeakerAgent.
> SpeakerAgent: Update version 1.1

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Change the policy to identify media content from token-based
to URL-based.
> AudioPlayerAgent: Change media content identification

- examples/standalone/nugu_sample.cc
- include/clientkit/nugu_client.hh
- include/clientkit/nugu_core_container_interface.hh
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
- src/core/nugu_core_container.cc
- src/core/nugu_core_container.hh
Because, in ICapabilityHelper, the getFocusManager function
is already defined and it's possible to access by NuguCoreContainer,
there are no need to define another same function in NuguClient.
Also, it should remove the related function which is defined
in NuguCoreContainer. (It's same case about getDirectiveSequencer.)
Signed-off-by: kimhyungrok <hr97gdi@gmail.com>
> NuguClient:Remove getFocusManager in NuguClient

- src/base/nugu_log.c
Fix to ignore module filtering for error level logs.
> base: fix module filtering for error level log

- include/base/nugu_directive.h
- src/base/nugu_directive.c
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/core/tts_player.cc
- tests/test-nugu-directive.c
There is a variation in performance because the size of the first of
the attachment data coming in the TTS response is not uniform.
This patch attempts to ensure constant performance for the first data
output by setting limits (4200 bytes) to the smallest of the first data
from multiple scenario cases.
> tts: set size limit for the 1st attachment

- plugins/portaudio.c
Currently, when a pcm is requested to be played, the playing status
event is immediately emitted even if there is no received pcm data.
To make profiling analysis more accurate, the event occurrence time
is changed to the time that the actual first pcm data is output.
> plugin: fix pcm playing status in portaudio

- include/clientkit/capability.hh
- include/clientkit/capability_helper_interface.hh
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/capability/system_agent.cc
- src/capability/system_agent.hh
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
- src/core/capability_helper.cc
- src/core/capability_helper.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
Change the current return type 'void' to 'bool' to check result for
getProperty(), getProperties(), receiveCommand() and sendCommand() APIs.
> capability: fix return type for property, command

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/clientkit/capability.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/directive_sequencer.cc
It change the time of parsing ASR ExpectSpeech directive
from onHandleDirective() to onPreHandleDirective().
It fix to call nugu_directive_unref() in appropriate
location at DirectiveSequencer destructor.
It remove the unnecessary header in ASRAgent.
Signed-off-by: kimhyungrok <hr97gdi@gmail.com>
> ASR:Adjust handling ExpectSpeech

- src/core/playstack_manager.cc
It change the converting way of PlayStackLayer enum to string
from condition check to using const map.
Also, it remove PlayStackLayer::None case, because it's useless.
> PlayStack:optimize PlayStackManager Debug

- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
The API name and functionality have changed since the specification has
been modified for Server Play. The application should call control
functions such as repeat, random play, etc. with the current values.
> AudioPlayerAgent: Modify control function

- src/capability/audio_player_agent.cc
There was a bug that AudioPlayerAgent did not stop, and fixed it.
> AudioPlayerAgent: Fix the bug.

- src/capability/text_agent.cc
The `property` is removed in specification.
> TextAgent: Remove unused field

- src/core/session_manager.cc
- src/core/session_manager.hh
- tests/core/test-core-session-manager.cc
It upgrade to be possible to handle Participation
of Multi-Agent about session activation/deactivation.
For example, when the received directives are composed
of ASR and Display, both agents could activate or
deactivate session. Because the session is active
if any agent participate, for deactivating session,
all agents have to deactivate.
> SessionManager:Upgrade to handle Multi-Agent Participation

- src/capability/asr_agent.cc
When the ExpectSpeech is triggered by TextRequest in TextAgent,
the listening is not operated correctly, because TextAgent
set asr_cancel flag true previously.
So, it needs to reset that flag when handling ExpectSpeech.
> ASRAgent:bug fix about cancel

- include/clientkit/capability.hh
add missing `override` annotation to `notifyEventResponse` API
in the `capability.hh` header file.
> capability: add missing override annotation

- include/base/nugu_network_manager.h
- src/base/nugu_network_manager.c
- src/capability/system_agent.cc
- src/capability/system_agent.hh
Add 'ResetConnection' directive to SystemAgent. When receiving this
message from the server, the SDK should immediately disconnect the
current connection and seamlessly start a new connection from the
device-gateway-registry step.
The following is an example of network state change event according
to network control.
Connect:
DISCONNECTED -> CONNECTING -> CONNECTED or DISCONNECTED
Disconnect:
CONNECTED -> DISCONNECTED
Handoff:
CONNECTED -> CONNECTING -> CONNECTED or DISCONNECTED
ResetConnection:
CONNECTED -> CONNECTING -> CONNECTED or DISCONNECTED
> capability: add ResetConnection to SystemAgent

- src/core/directive_sequencer.cc
There was a bug where the audio/visual map's dialog_id key was not
deleted when calling the `cancel` API.
> core: add missing map erase to directive sequencer

- include/clientkit/capability.hh
- include/clientkit/playstack_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/test-core-playstack-manager.cc
If the previous dialog which is not handled exist,
it fix to handle that proper way.
1) If playstack is stacked condition, it handle to complete.
2) If playstack is not stacked condition, it handle to cancel.
Because, the processDirective of Capability execute important flow
about directive, it change to prevent overriding in derived class.
When the AudioPlayerAgent go to background focus,
if the player state is PREPARE, it cause skip to pause player,
so, media is playing continously.
For preventing that situation, it add conditions about PREPARE, READY case.
> dialog:fix to handle previous dialog

- src/base/nugu_pcm.c
- src/base/nugu_player.c
- src/base/nugu_plugin.c
- src/base/nugu_recorder.c
Currently, the plugin initialization order is applied equally to the
deinitialization order, which can cause problems when there is a
dependency relationship.
Therefore, when deinitialization, change to call `unload` function
in reverse order.
As-is:
init a -> init b -> ... -> de-init a -> de-init b
To-be:
init a -> init b -> ... -> de-init b -> de-init a
> plugin: fix plugin de-initialize order

- src/capability/tts_agent.cc
There is a bug if the directive `TTS.Speak` is received during
speaking, the event `TTS.SpeechStopped` is sent with the new dialog id
to set RDRID, not previous dialog id.
> RDRID: fix the bug

- examples/standalone/nugu_sample.cc
- include/base/nugu_network_manager.h
- include/clientkit/network_manager_interface.hh
- src/base/nugu_network_manager.c
- src/clientkit/network_manager_interface.cc
- src/core/network_manager.cc
There is no place where the onEventSent callback is used, and it seems
more useful to use the callback before sending the event and before
sending the attachment.
> network: fix event send callback

- src/capability/audio_player_agent.cc
The backend server is needed information about play service id for
routing the audioplayer event to Play. AudioPlayerAgent added the
play service id to context information.
> AudioPlayerAgent: Update version 1.4

- include/clientkit/session_manager_interface.hh
- src/clientkit/capability.cc
- src/core/session_manager.cc
- src/core/session_manager.hh
- tests/core/test_core_session_manager.cc
It add clear method in SessionManager for removing
all session info if necessary.
That is applied in handling previous directive.
> session:apply session clearance

- examples/profiling/main_prof.cc
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- src/core/directive_sequencer.cc
- src/core/playstack_manager.cc
Removed reported issue as belows:
* clang-analyzer-core.CallAndMessage
* performance-unnecessary-copy-initialization
* clang-analyzer-core.NullDereference
* cert-err34-c
* cert-err58-cpp
> Remove static analysis(clang-tidy) report

- include/capability/text_interface.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
It apply const string reference on parameter
of requestTextInput method in ITextHandler and dervied TextAgent.
> TextAgent:apply const reference on requestTextInput

- include/clientkit/playstack_manager_interface.hh
- src/clientkit/capability.cc
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/test_core_playstack_manager.cc
Even if the playstack is stacked conditions, if the previous
directive has ASR-ExpectSpeech, that directive has to be canceled.
So, it export hasExpectSpeech method in PlayStackManager
and add to second condition which check to process previous directive.
> capability:add condition about processing previous directive

- examples/profiling/main_prof.cc
- src/base/nugu_prof.c
Add testcase name and timestamp to test results. Also, to prevent
parsing errors in some analysis tools, the space(' ') in the
profiling name has been changed to '_'.
> profiling: enhance the csv reporting result

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
The paremeter 'expected' of startRecognition(bool expected)
is never used in method, and that method is not defined in IASRHandler.
So, there are no need to define that method separately.
That method is merged to startRecognition(AsrRecognizeCallback callback).
> ASRAgent:remove unnecessary method

- examples/standalone/capability/session_listener.cc
- examples/standalone/capability/session_listener.hh
- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- include/capability/session_interface.hh
- src/capability/session_agent.cc
- src/capability/session_agent.hh
- src/core/session_manager.cc
- tests/core/test_core_session_manager.cc
It add ISessionListener for receiving session state in session_interface.
If the derived class which implements ISessionListener
is added to ISessionHandler, in Application,
it's possible to receive callback about session state.
> Session:notify session state

- src/capability/audio_player_agent.cc
In the audio player, when the user stops or pauses speech during media
playback, the media is partially played.
> AudioPlayerAgent: fix the focus bug

- src/capability/session_agent.cc
- src/core/session_manager.cc
- src/core/session_manager.hh
It fix the issues which are detected from static analysis(clang-tidy).
* call to virtual function during destruction
* cannot pass object of non-trivial type 'const std::string'
> fix static analysis report

- include/clientkit/focus_manager_interface.hh
- src/capability/asr_agent.cc
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test_core_focus_manager.cc
The mediaplayer is played for a while caused by focus when the
text-to-speech is ended during conversation.
> Focus: Add hold/unhold functions

- src/capability/tts_agent.cc
Because, the call or alert layer has related TTS,
when TTS play is finished, that playstack has to be remove also.
So, it fix the removal condition of playstack in TTSAgent.
> PlayStack:fix playstack removal condition

- src/capability/session_agent.cc
It add to unhold DIALOG_FOCUS_TYPE when session is deactived,
regardless of normal condition or canceled situation.
> Session:unhold focus when session deactivated

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/system_listener.cc
- examples/standalone/capability/text_listener.cc
- examples/standalone/capability/text_listener.hh
- examples/standalone/nugu_sample.cc
- examples/standalone/nugu_sample_manager.cc
Because, it's possible to show full debug log
by nugu sample launch option (./nugusdk_start_sample nugu_sample d),
it doesn't need to show much log by default.
So, it simplify the default log in nugu_sample.
> nugu_sample:remove unnecessary log

- include/base/nugu_log.h
Fixed an error in ANSI code being output due to NORMAL macro even when
ANSI mode was not used.
> log: fix ansi code for normal mode

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- include/clientkit/directive_sequencer_interface.hh
- src/clientkit/capability.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/core/test_core_directive_sequencer.cc
There is currently no callback for directive cancel, so the Capability
agent has no way of know if the directive has been canceled.
Therefore, in order to solve the above issue, a directive cancellation
event is added.
> core: add cancel callback to DirectiveSequencer

- packaging/bionic/libnugu-examples.install
- packaging/xenial/libnugu-examples.install
Some example programs are use the '/usr/share/' path to load data files.
But, the path is not listed in the instalation description file for
DEB package.
> build: add missing install files to package

- examples/standalone/nugu_sample_manager.cc
- include/capability/text_interface.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
It some case, even if session is progressive,
it has to be possible to handle another text command
which is not related to current session.
So, it add the parameter on requestTextInput in TextHander
which is possible to include dialog attribute selectively.
> TextInterface:add option for dialog attribute on requestTextInput

- src/core/session_manager.cc
It add to remove all listeners when the destructor
of SessionManager is called.
> session:add to remove SessionManagerListener finally

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/clientkit/capability.cc
When the current handling directive about ASR ExpectSpeech is canceled,
caused by text input command, the previous attributes info is not cleared.
So, it fix to clear that attributes when the current directive is canceled.
> ASR:fix to clear ExpectSpeech attributes

- CMakeLists.txt
- plugins/CMakeLists.txt
- plugins/gstreamer_pcm.c
Gstreamer is support the volume control for pcm player. If you want
to enable the gstreamer pcm player, there is 2 options.
1. Remove the `portaudio_pcm_*.so`
2. Set default pcm player driver as below.
```
NuguPcmDriver* driver = nugu_pcm_driver_find("gstreamer_pcm");
nugu_pcm_driver_set_default(driver)
```
> Pcm: Add pcm player plugin using gstreamer

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- include/capability/speaker_interface.hh
- src/capability/speaker_agent.cc
If the property is set as uncontrollable, the speaker agent transmits
the event with context information excluding the property.
> SpeakerAgent: Set unable control

- plugins/portaudio_pcm_async.c
The `portaudio_pcm_async` was modified to be the default pcm player.
> portaudio: Set default pcm driver

- src/capability/text_agent.cc
- src/capability/text_agent.hh
If the `playServiceId` field exists in the `Text.TextSource` directive,
the `Text.TextInput` event must be transmitted by forcibly setting it
to a newly received value instead of the internally managed
`playServiceId` value.
Also, `playServiceId`, `domainTypes`, `asrContext` fields received from
`ASR.ExpecSpeech` must not be included in `Text.TextInput` event.
> capability: add playServiceId to Text.TextSource

- src/capability/asr_agent.cc
When the audioplayer is playing music, the state of the audioplayer is
`PLAYING` even if the user invokes asr recognition.
> ASRAgent: Fix the context information

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
The `timeoutInMilliseconds` field is removed because it is no longer
needed.
> ASRAgent: remove unused field

- include/base/nugu_network_manager.h
- src/base/network/dg_server.c
- src/base/network/dg_server.h
- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
- src/base/nugu_event.c
- src/base/nugu_network_manager.c
- tests/test_nugu_event.c
The following 'Last-Asr-Event-Time' HTTP header field was added in
the device-gateway server protocol specification.
Last-Asr-Event-Time: {IMF-fixdate format}
Example:
Last-Asr-Event-Time: Sun, 06 Nov 1994 08:49:37 GMT
This field is updated whenever there is an ASR event transmission.
And, if the ASR event has not yet occurred, it is not sent.
> base: add Last-Asr-Event-Time HTTP header

- include/clientkit/playstack_manager_interface.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
It change return type of add() for checking result.
It expose IStackTimer which is used as context holding timer
to be able to replace to customized timer (It's used for test, mainly).
It apply stack replacement and notification flow.
> playstack:update PlayStackManager

- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
fix the 'commmand' to 'command'
> capability: fix typo in the audio_player_agent

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/CMakeLists.txt
- tests/core/test_core_playsync_manager.cc
It add PlaySyncManager for managing context and sync flow
between related capability agents like TTS, Display, AudioPlayer.
Because, it has to control playstack simultaneously,
the PlayStackManager is included innerly.
> playsync:add PlaySyncManager

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- include/capability/audio_player_interface.hh
- include/capability/display_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Display Interface was added to support display devices. When creating
a DisplayAgent outside the SDK, refer to it, and the Application can
receive Display-related information by registering a Listener to
the AudioPlayerAgent.
> Capability: add display interface

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add onDataChanged callback in IPlaySyncManagerListener
for receiving changed extra data.
The returned extra datas are composed by previous and new datas.
> playsync:add onDataChanged callback

- src/capability/asr_agent.cc
Asr's error code was added to `ASR.NotifyResult`.
> ASRAgent: Add asr error code

- src/capability/audio_player_agent.cc
It fix the bug about handling sync data as adding null check
for display listener instance.
> AudioPlayer:fix sync data handling bug

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
When it receive onSyncState callback from PlaySyncManager about release,
if another directive is preprocessing, it skip executing suspend,
because related action is handled in processDirective.
> tts:add condition not to handle sync release

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Because, the render info is maintained by single object,
it has a problem not to refresh next or previous song's info.
So, it change to manage render info to map container
which is possible to handle multiple render infos.
> AudioPlayer:update to manage render info to container

- src/capability/text_agent.cc
- src/capability/text_agent.hh
It update the version of TextAgent from 1.2 to 1.3.
Also, it merge two overloading sendEventTextInput method to one.
> Text:update capability version to 1.3

- src/capability/audio_player_agent.cc
Fixed the AudioPlayerAgent not notifying application of the `Playing`
state in the following cases:
when the audioplayer paused due to wakeup and then resumes playing.
> AudioPlayerAgent: Notify event

- src/capability/text_agent.cc
- src/capability/text_agent.hh
It apply the default value(true) on include_dialog_attribute parameter
of sendEventTextInput method.
> text:apply default value on sendEventTextInput parameter

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
It update to be possible to refresh display render info
when context is already synced in DisplayAgent.
When render datas exist in both Display And AudioPlayer,
it set to have priority in Display, so ignore AudioPlayer's data.
> Display:update to refresh display render info

- examples/standalone/nugu_sample_manager.cc
- include/capability/text_interface.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
As another agents or components have to send token when sending TextInput event,
it add token parameter on requestTextInput method.
> Text:add token parameter on requestTextInput

- examples/standalone/nugu_sample.cc
- include/clientkit/interaction_control_manager_interface.hh
- src/core/capability_manager.cc
- src/core/interaction_control_manager.cc
- src/core/interaction_control_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_interaction_control_manager.cc
- tests/core/test_core_playsync_manager.cc
It add the callback which is possible to be notified
when the received directive has multi-turn (ASR.ExpectSpeech).
It could be checked before ASR states is changed from busy to idle.
```
==================================================
[Dialog - ASR] FOREGROUND (priority: 100)
==================================================
[ASR][id:0cadf95d9d01d9dfebc42a0e0791125b] LISTENING
[ASR][id:0cadf95d9d01d9dfebc42a0e0791125b] RECOGNIZING
[ASR][id:0cadf95d9d01d9dfebc42a0e0791125b] BUSY
[ASR][id:0cadf95d9d01d9dfebc42a0e0791125b] onComplete > NUGU DJ 열어줘
>>> [multi-turn] has multi-turn
[ASR][id:0cadf95d9d01d9dfebc42a0e0791125b] IDLE
==================================================
[Dialog - ASR] NONE (priority: 100)
================================================== …
```
> interaction:notify whether directive has multi-turn

- examples/standalone/nugu_sample_manager.cc
It change NuguSampleManager codes about reset std::pair
for guarantee compatibility about build environment.
> sample:update for compatibility about build environment

- src/core/interaction_control_manager.cc
- src/core/interaction_control_manager.hh
- tests/core/test_core_interaction_control_manager.cc
It add the reset test for InteractionControlManager in unit test.
Also, it add the getAllRequesters method in InteractionControlManager
for retrieving container of requester.
> interaction:add reset test for InteractionControlManager

- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the reset test for PlaySyncManager in unit test.
Also, it add the hasPostPoneRelease method in PlaySyncManager
for retrieving PostPoned release info.
> playsync:add reset test for PlaySyncManager

- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/test_core_playstack_manager.cc
It add the reset test for PlayStackManager in unit test.
Also, it add the getFlagSet method in PlayStackManager
for retrieving inner private flags.
> playstack:add reset test for PlayStackManager

- src/core/playstack_manager.cc
- tests/core/test_core_playstack_manager.cc
It fix to stop inner timer when resetting PlayStackManager
by calling reset method.
> playstack:fix to stop timer when resetting PlayStackManager

- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
It add the getCapabilityHandler method in NuguClient for retrieving
requested instance of CapabilityAgent.
```
auto nugu_client(std::make_shared<NuguClient>());
auto text_handler(dynamic_cast<ITextHandler*>(nugu_client->getCapabilityHandler("Text")));
```
> NuguClient:add getCapabilityHandler

- examples/CMakeLists.txt
- examples/response_filter/CMakeLists.txt
- examples/response_filter/filter.cc
- examples/response_filter/filter.h
- examples/response_filter/main.cc
This is an example of substituting the desired response for a speech
that is not supported by the server through a filter.
> examples: add asr/text request filter

- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It add to show current playstack info on nugu sample UI.
The playstack info is shown on above select command input.
```
=======================================================
NUGU SDK Command (Connected)
=======================================================
[ w] : start listening with wakeup
[ l] : start listening
[ s] : stop listening/wakeup
[ t] : text input
[t2] : text input (ignore dialog attribute)
[ m] : set mic mute
[sa] : suspend all
[ra] : restore all
-------------------------------------------------------
[ i] : initialize
[ d] : deinitialize
[ q] : quit
-------------------------------------------------------
[PlayStack] nugu.builtin.music   <-- This is current playstack info.
Select Command > 
```
> nugu_sample:add to show playstack info

- include/base/nugu_timer.h
- include/clientkit/nugu_timer_interface.hh
- src/base/nugu_timer.c
- src/core/nugu_timer.cc
- src/core/nugu_timer.hh
- tests/core/test_core_nugu_timer.cc
- tests/core/test_core_nugu_timer_mock.cc
- tests/test_nugu_timer.c
The NUGU Timer is supported the loop property as below.
// base/nugu_timer.h
nugu_timer_set_loop(timer, 1);
// clientkit/nugu_timer_interface.hh
INuguTimer::setLoop(true);
> Timer: Add loop property

- examples/response_filter/filter.cc
- examples/response_filter/main.cc
There is a memory leak bug for NuguDirective in onPreHandle callback.
So fixed it.
> examples: fix memory leak in the asr/text filter

- include/clientkit/playsync_manager_interface.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the registerCapabilityForSync method in PlaySyncManager
which is possible to register capability for sync.
It change the handling previous stack info in PlayStackManager
to remove another stack except Media Layer in stacked condition.
> playsync:update playsync and playstack management for handling Alerts

- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
It add the maps of SpeakerType and name string for improving
to retrieve the matched SpeakerType and name string efficiently.
Someday, if it needs to add new SpeakerType, it's done just adding
new SpeakerType and name string item to speaker_names_for_types map.
> SpeakerAgent:compose SpeakerType and name string maps

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
AudioPlayer keeps context information like token even when the media
services are deactivated.
> AudioPlayer: Clear context information

- include/clientkit/capability.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/capability.cc
As some capability agents are operated with sync, there are cases
which need to to handle sync state result separately.
So, it fix not to handle the sync state result
if the condition is not satisfied in TTSAgent.
Also, it update to cancel previous directive
if the sync state result needs to suspend TTS play.
> TTS:fix handling sync state result

- src/core/playsync_manager.cc
It fix to execute clearPostPonedRelease firstly,
when preparing sync for suspending previous release action.
> playsync:fix playsync postpone release

- src/capability/tts_agent.cc
The TTSAgent should send the below events even if the play service id is not included.
TTS.SpeechStarted
TTS.SpeechFinished
TTS.SpeechStopped
> TTSAgent: Update interface v1.3

- include/clientkit/focus_manager_interface.hh
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test_core_focus_manager.cc
The NUGU sound policy is changed that focus has request and release
priority as belows. The focus manager is added focus request priority
for this feature.
| Num | Request Order |  Release Order |
|:----------:|:-------------:|:------:|
| 1 | Call, ASR(User) | Call |
| 2 | Alerts, Info | ASR(User) |
| 3 | Media | ASR(DM), Alerts, Info |
| 4 | ASR(DM) | ASRBeep |
| 5 | ASRBeep, Sound | Media, Sound, Dummy |
| 6 | Dummy | Empty |
For examples, `Info` focus is can steal the `ASR(Users)` focus even
if it is lower release priority than `ASR(Users)` focus.
> FocusManager: Added focus request priority

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/display_listener.hh
- include/capability/display_interface.hh
- include/clientkit/playsync_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It add the flag in clearDisplay method of IDisplayListener
for checking whether the next display to render exists.
Because, the next render info is acquired from playstack,
it add related methods in PlaySyncManager and PlayStackManager.
```
// in nugu_sample log
[Display] clear display template
id:1604050384750876
unconditionally:1
has_next:1 <-- next display to render exists
```
> playsync:add flag for check next display to render exists

- examples/standalone/capability/audio_player_listener.cc
- examples/standalone/capability/audio_player_listener.hh
- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/display_listener.hh
- include/capability/display_interface.hh
It change the AudioPlayerListener in standalone example
from implementing APIs about display to inheriting DisplayListener
for removing duplicate code.
> example:refactoring AudioPlayerListener

- tests/core/test_core_playstack_manager.cc
As some methods in PlayStackManager test are named by camel case,
it's not consistent with another's.
So it change to the combination of lowercase and underscore
like other methods.
> playstack:renaming methods of PlayStackManager test

- src/core/nugu_timer.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
In StackTimer of PlayStackManager, after the timer is activated,
is_started flag is not reset, it invoke abnormal behavio in some case.
So, It override notifyCallback method from NUGUTimer
and set is_started to false when this method is called.
> playstack:reset PlayStackManager Timer started flag

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
The server is sent the directive `System.Exception` when the event
`ASR.StopRecognize` is sent after the directive stream is closed.
To prevent this, ASRAgent notify to the server by sending attachment
with end instead of closing the directive stream forcely.
> ASRAgent: Fixed the server response error

- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/test_core_playstack_manager.cc
It some case, even if it has no display rendering info,
it decide to has that info.
So, it adjust to check whether the directive has Display
or AudioPlayer when new playstack is added for correct judgement.
> playstack:adjust checking next display info

- src/capability/text_agent.cc
- src/capability/text_agent.hh
The `TextRedirect` directive was added to v1.4 spec.
If `targetPlayServiceId` value exists in the directive,
`playServiceId` value should be replaced with that value.
> capability: update Text interface to v1.4

- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It add the setPlayStackHoldTime in PlayStackManager
for changing playstack hold time. (Default normal:7s, long:600s)
> playstack:Add method for changing playstack hold time

- src/capability/audio_player_agent.cc
AudioPlayerAgent still has player's last state even if the AudioPlayer
is released by PlaySyncManager.
> AudioPlayerAgent: Stop player with sync release

- src/capability/tts_agent.cc
When handling TTS.Stop directive, if TTS.Speak directive
is processing, that previous directive is canceled.
Because, the member variable 'speak_dir' has the pointer
of previous directive even if that is canceled,
it cause dangling problem in TTS.Stop.
So, it fix to refresh 'speak_dir' for pointing correct object
when handling TTS.Stop.
> TTS:fix handling TTS.Stop directive

- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
If destroyDirective method is called more than once,
it could be operated abnormally.
So, it add the validation check and make a group the related flow.
> capabiliy:reinforce destroyDirective

- include/capability/asr_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
Because it needs to get or set EPD attribute of SDK in Application,
it add setEpdAttribute and getEpdAttribute methods in IASRHandler.
Also, the getEpdSilenceInterval method is replaced by getEpdAttribute.
> ASRAgent:Add EPD Attribute setter/getter

- include/clientkit/playsync_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It apply the changed media pause playstack policy
which is maintained 10m' timer, even if any events are occurred.
That policy is applied to explicit and implicit both cases.
> AudioPlayer:apply media pause playstack policy

- src/base/network/http2/directives_parser.cc
- src/base/network/http2/http2_request.c
- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_event_attachment.c
- src/base/network/http2/v2_events.c
- src/base/nugu_directive.c
- src/base/nugu_event.c
- src/base/nugu_network_manager.c
- src/base/nugu_prof.c
- src/base/nugu_uuid.c
Replace all `strdup` with safe(NULL checked) `g_strdup` function.
> base: change strdup to g_strdup

- src/core/directive_sequencer.cc
- src/core/tts_player.cc
- tests/core/test_core_directive_sequencer.cc
Add the missing `#include` for some header files.
> core: add missing header includes

- src/capability/audio_player_agent.cc
The context is still meaningful to PlayRouter even if the playsync
is released.
> AudioPlayerAgent: Rollback about context clear

- include/clientkit/capability.hh
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/clientkit/capability.cc
It some case, it has to destroy directive by agent,
and the "has_attachment" variable is used for this purpose
in TTSAgent and AudioPlayerAgent.
But, in another case, even if it doesn't have attachment,
as it need to destroy directive byself,
the "has_attachment" variable name is not appropriate in this case.
So it change that variable name to destroy_directive_by_agent.
> capability:change has_attachment variable name

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
- include/capability/capability_factory.hh
- include/capability/utility_interface.hh
- src/capability/capability_factory.cc
- src/capability/utility_agent.cc
- src/capability/utility_agent.hh
It add utility interface(It's composed by IUtilityHandler and
IUtilityListener) and UtilityAgent.
It apply Utility Interface v1.0 spec.
For correct activation, it has to update DirectiveSequencer.
So, in this commit, it skip constructing agent by NuguClient.
> Utility:Add Utility Interface and Agent.

- src/capability/text_agent.cc
As the request for handling blank text,
it remove validation check for text field size.
Also, the token field is not mandatory, there are no reason
> TextAgent:remove validation check for text and token

- include/base/nugu_directive.h
- include/clientkit/directive_sequencer_interface.hh
- src/base/nugu_directive.c
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/test_nugu_directive.c
The blocking policy for the directive has been modified to be set in
the NuguDirective itself.
When the DirectiveSequencer receives a new directive, it sets a
blocking policy on the directive.
> base: add policy to NuguDirective

- src/capability/utility_agent.cc
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/core/test_core_directive_sequencer.cc
The `BlockingMedium::ANY` type was added to the spec document.
This type is blocked by all other types(Audio/Visual/None/Any),
and all other types can be blocked.
e.g. When the sequencer receives a list of directives as below
for the dialog ID:
[
1:Audio/block,
2:Any/block,
3:None/non-block,
4:Any/block,
5:None/non-block
]
Directives are processed in the following order.
Start-1 -> Complete-1
-> Start-2 -> Complete-2
*)-> Start-3 -> Complete-3
-> Start-4 -> Complete-4
-> Start-5 -> Complete-5
*) Even in the case of a non-block, if there is an ANY behind it,
the ANY must be processed after the non-block is completed.
> core: add ANY medium to DirectiveSequencer

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/display_render_helper.cc
- src/capability/display_render_helper.hh
In DisplayAgent and AudioPlayerAgent, the code about rendering
exist duplicately and also it's not commonized.
So, it add DisplayRenderHelper for handling rendering singly.
> DisplayRender:Add DisplayRenderHelper

- src/core/directive_sequencer.cc
- tests/core/test_core_directive_sequencer.cc
The DirectiveSequencer calls `handleDirective` at idle time, but there
was a bug in which the list was changed in the middle when `complete`
was processed immediately within it.
To fix the above issue, changed to use after copying the list in the
idle callback.
> core: fix DirectiveSequencer idle callback bug

- src/core/directive_sequencer.cc
There was a bug where the memory of the pending directives was not
released when the DirectiveSequencer was reset.
To fix above bug, the code was modified to release(unref) remain
all NuguDirectives in the `msgid_lookup` table on `reset()`.
> core: fix memory leak in DirectiveSequencer

- src/capability/audio_player_agent.cc
Because, AudioPlayer Interface 1.5 spec is already applied using by
PlaySync flow, it just update capability version number from 1.4 to 1.5.
* PlaybackStopped event reason according by PlayServiceId
1. same : PLAY_ANOTHER
2. differenct :STOP (It's handled by PlaySyncManager.)
> AudioPlayer:apply AudioPlayer Interface 1.5

- src/core/session_manager.cc
- tests/core/test_core_session_manager.cc
If the several sessionIds which are matched with same playServiceId
exist, as the context policy, it has to select a recent received one.
So, it update to extract the latest sessionId in same playServiceId.
> session:compose recent sessionId in same playServiceId

- src/capability/display_agent.cc
- src/capability/display_agent.hh
- tests/core/test_core_session_manager.cc
In DisplayAgent, there are some case which needs to
maintain multi-session until display is closed.
So, it apply mutli-session maintenance flow in DisplayAgent.
Because, it's hard to do an acceptance test in current situation,
it replace to do similar test in test_core_session_manager.
> session:apply multi-session maintenance flow

- src/capability/chips_agent.cc
- src/capability/chips_agent.hh
It apply the directive blocking policy about Chips.
It would block Audio medium for Render directive.
> Chips:apply directive blocking policy

- examples/standalone/capability/chips_listener.cc
- examples/standalone/capability/chips_listener.hh
- include/capability/chips_interface.hh
- src/capability/chips_agent.cc
As, all payload of Render directive have to be delivered to app,
it extends the ChipContent model to include playServiceId, target.
And it change the model name to ChipsInfo.
> Chips:extends ChipContent Model to ChipsInfo

- src/core/directive_sequencer.cc
Even if the some directive is not handled, because
it's possible to execute the specific flow in preHandling time,
it needs to receive cancelDirective callback about pending list
when the related dialog is canceled.
So, it change to notify cancelDirective when removing pending list.
> DirectiveSequencer:change to notify cancelDirective about pending list

- .gitignore
- src/base/nugu_pcm.c
- src/base/nugu_player.c
- src/base/nugu_recorder.c
- src/core/audio_recorder_manager.cc
- src/core/speech_recognizer.cc
- src/core/wakeup_detector.cc
Fixed a problem in which the NUGU SDK was hangup if specific drivers
such as pcm, player, and recorder were not installed.
Speech recognizer and wakeup detector have their own thread that does
not terminate until the instance is destroyed, but there was an issue
where the thread terminated if the recorder was not played,
and this was fixed.
> Remove plugin assert

- examples/standalone/capability/extension_listener.cc
- examples/standalone/capability/extension_listener.hh
- include/capability/extension_interface.hh
- src/capability/extension_agent.cc
- src/capability/extension_agent.hh
It update the extension interface API to match with
another platform (Android, iOS).
Because, the coding convention of some methods are incorrect,
it fix to obey rule.
> extension:match extension interface API

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- src/clientkit/capability.cc
It add the setCancelPolicy API in ICapabilityInterface
for setting directive cancel policy.
```
// example
ITTSHandler->setCancelPolicy({true});  // set cancel all (default)
ITTSHandler->setCancelPolicy({false, {"PhonCall.makeCall", "PhoneCall.endCall});  // set cancel about specific groups
```
> capability:add setCancelPolicy API

- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sample_manager.hh
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It add to show the current mic status (ON/OFF).
```
=======================================================
NUGU SDK Command (Connected)
=======================================================
[ w] : start listening with wakeup
[ l] : start listening
[ s] : stop listening/wakeup
[ t] : text input
[t2] : text input (ignore dialog attribute)
[ m] : set mic mute
[sa] : suspend all
[ra] : restore all
-------------------------------------------------------
[ i] : initialize
[ d] : deinitialize
[ q] : quit
-------------------------------------------------------
[MIC] ON / [PlayStack] 
Select Command >
```
Also, it clean the code about composing focus configuration.
> nugu_sample:show mic status on UI

- include/clientkit/directive_sequencer_interface.hh
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/core/test_core_directive_sequencer.cc
Currently, the cancellation API provided by DirectiveSequcner cancels
the entire directive corresponding to the dialog ID, but an API that
cancels only specific directives is also required.
So, add the following API.
bool cancel(const std::string& dialog_id,
std::set<std::string> groups)
For groups, you can use a list of strings in the form of
`"{Namespace}.{Name}"` such as `"PhoneCall.MakeCall"`.
cancel("dlg-1", { "PhoneCall.MakeCall", "PhoneCall.EndCall" });
> core: add cancel by group to directive sequencer

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
It update to include all capability's context about some events.
* Display.ElementSelected
* AudioPlayer.*CommandIssued
* AudioPlayer.PlaybackFinished
* ASR.ListenTimeout
> context:change context scope of some events

- src/core/playsync_manager.cc
It add to clear previous release timer when preparing sync.
> playsync:add clear holding when preparing sync

- src/clientkit/capability.cc
It apply to cancel directives partially.
It's possible to set directive groups for canceling
using by setCancelPolicy API which is declared in ICapabilityInterface.
> Capability:apply partial cancel directives

- include/clientkit/playsync_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
As the term about layer is updated to activity in playstack policy,
it change all related code for matching with the policy.
> playstack:change playstack layer terms to activity

- src/capability/tts_agent.cc
It update handling TTS.Stop directive to release playsync
immediatley if the current TTS state is not playing.
> TTS:update handling TTS.Stop

- src/base/network/http2/v2_events.c
add 'nugusdk.boundary.' prefix to multipart boundary.
> base: apply nugu sdk multipart rule

- include/clientkit/interaction_control_manager_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/text_agent.cc
- src/capability/text_agent.hh
- src/core/interaction_control_manager.cc
- src/core/interaction_control_manager.hh
- tests/core/test_core_interaction_control_manager.cc
When handling Text.TextRedirect directive,
because it needs to maintain processing state (multi-turn),
it update to be controlled by InteractionControlManager.
> TextAgent:handle TextRedirect by InteractionControl

- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It add a few commands on nugu_sample UI
which are possible to control speaker volume and mute.
It compose the SpeakerController for control speaker separately.
```
=======================================================
NUGU SDK Command (Connected)
=======================================================
[ w] : start listening with wakeup
[ l] : start listening
[ s] : stop listening/wakeup
[ t] : text input
[t2] : text input (ignore dialog attribute)
[ m] : set mic mute/unmute
[sm] : set speaker mute/unmute
[ +] : set speaker volume up
[ -] : set speaker volume down
[sa] : suspend all
[ra] : restore all
-------------------------------------------------------
[ i] : initialize
[ d] : deinitialize
[ q] : quit
-------------------------------------------------------
[Volume] 100 / [MIC] ON …
```
> nugu_sample:add speaker volume/mute control

- src/capability/audio_player_agent.cc
Even if there are no existing render info in AudioPlayerAgent,
it's not reasonable to log error.
So, it adjust log level and description.
> AudioPlayer:adjust log level about render info

- src/core/media_player.cc
When the media player is muted, in some case,
the media is played by previous volume level in short time.
For supplementation this,
it apply the seek with the purpose of avoiding malfunctional frame.
> MediaPlayer:supplement media player mute

- examples/oob_setup/nugu_oob_server.py
Remove the duplicated '/' to fix oauth error.
as-is) URL//v1/auth/oauth/token
to-be) URL/v1/auth/oauth/token
> examples: fix url issue in nugu_oob_server.py

- examples/standalone/capability_collection.cc
- src/capability/audio_player_agent.cc
It update to add the AudioPlayer/Display listener at once
in setCapabilityListener because it's same object generally.
If two listeners are different, it could add by
addListener(AudioPlayer), setListener(Display) separately.
> AudioPlayer:set AudioPlayer/Display listener at once

- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- include/capability/asr_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
It apply the ASR interface v1.5 NDI spec.
(state, initiator fields are added in context.)
* state : state of asr like IDLE, LISTENING,...
* initiator : initiator of ASR whether wakeup of button tap.
It addition, it add the engine field in context which is already
defined in v1.0 by option, for managing the spec fully.
> ASR:apply ASR interface v1.5

- src/capability/audio_player_agent.cc
It apply the AudioPlayer Interface v1.6.
Because, the updated spec is about display template (not parsing in sdk)
there is no need to handle directly.
So, it just update capability interface version to 1.6.
> AudioPlayer:apply AudioPlayer Interface v1.6

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/display_render_helper.cc
- src/capability/display_render_helper.hh
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- src/capability/text_agent.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
It apply the noexcept specifier in method
which guarantee handling exception itself.
It change the share_ptr to unique_ptr in the case
which is no need to share resource.
It change throwing exception from string to literal in parsingTextSource,
parsingTextRedirect of TextAgent, for avoiding bad allocation exception.
> capability:optimize method specifier and smart pointer usage

- src/capability/audio_player_agent.cc
It update parsing stop directive in AudioPlayerAgent to clear
cur_url variable which is used to save current media url.
> AudioPlayer:update parsing stop directive

- src/capability/audio_player_agent.cc
The media content should be played just once until finished but the
AudioPlayerAgent repeat the playback of media content when it has focus
on again after finished.
> AudioPlayer: Block repeat playback of media content

- .gitignore
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
If user requests music service during playing media, the media should be
expired. But the media is resumed when the AudioPlayer's focus state is
changed from `Background` to `Foreground` by release the TTS before it
receives the new `AudioPlayer.Play` directive.
> AudioPlayer: doesn't play the expired media

- src/capability/text_agent.cc
When receiving a Text command instead of a user's speech in a DM
situation, it should be confirmed that it is multi-turn. Otherwise, the
media could be played before the response to the Text command comes.
> Text: multi-turn

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
It change the type of handler and listener from shared_ptr
to unique_ptr for optimizing memory usages.
It extract the additional codes of composing speaker interface
to composeSpeakerInterface method for simplifying factory lambda.
> nugu_sample:optimize CapabilityCollection

- src/core/focus_manager.cc
There was an issue where the focus was mixed when the focus was
controlled in the listener, and this has been fixed.
> Focus: fixed the recursive call bug

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the clear API in PlaySyncManager for removing all playstack info.
> PlaySync:Add clear API for removing playstack info

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
The `reason` field in the `PlaybackStopped` is filled `PLAY_ANOTHER`
when the audioplayer is stopped caused by next content in same play
service.
> AudioPlayerAgent: Fixed the version 1.5 spec

- src/capability/display_agent.cc
It apply the Display Interface v1.7.
Because, the updated spec is about template inner datas,
there are no need to handle that changes in SDK.
So, it just increase the Agent version to 1.7.
> Display:Apply Display Interface v1.7

- examples/standalone/capability/chips_listener.cc
- examples/standalone/capability/chips_listener.hh
- include/capability/chips_interface.hh
- src/capability/chips_agent.cc
- src/capability/chips_agent.hh
It apply the Chips Inteface v1.2.
It define the target and chips.type to enum class.
It update parsing render directive.
> Chips:Apply Chips Interface v1.2

- src/capability/audio_player_agent.cc
The NUGU SDK received `TTS.Speak` due to an invalid request about media
control in a state while the media service does not exist in the play
stack.
> AudioPlayer: fix command issue

- examples/profiling/main_prof.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- include/capability/asr_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
It apply the ASR interface v1.6 Spec.
It update onError method in IASRListener as adding argument
listen_timeout_fail_beep for check to play fail beep or not
when the listen timeout error's occurred.
> ASR:Apply ASR interface v1.6

- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
While handling listeners in range-based for loop,
because it's setting the element by value,
the copy is occurred always, so, it's not efficient.
So, it change to set element by const reference
for avoiding unnecessary resource usage by copy.
> [ASR,AudioPlayer] Change handling listeners in Range-based for loop

- examples/oob_setup/CMakeLists.txt
- packaging/bionic/libnugu-examples.install
- packaging/xenial/libnugu-examples.install
Remove the systemd service file for nugu_oob from default installation
list. Because this file is just an example and not mandatory.
> examples: remove oob systemd file from install

- include/base/nugu_network_manager.h
- include/clientkit/network_manager_interface.hh
- src/base/nugu_network_manager.c
- src/core/network_manager.cc
Add network connection type to support connection-oriented and
connectionless PoC.
This type value is set by the scope value of token payload through
token information (JWT format) analysis.
> network: add network connection type

- include/base/nugu_network_manager.h
- include/clientkit/capability.hh
- src/base/network/dg_server.c
- src/base/network/dg_server.h
- src/base/network/http2/v1_event.c
- src/base/network/http2/v1_event.h
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
- src/base/nugu_network_manager.c
- src/clientkit/capability.cc
The sync type event send method is no longer used, so remove it.
> network: remove event send with sync

- src/core/playstack_manager.cc
- src/core/playsync_manager.cc
It could be occured error depending on build option.
error: 'out_of_range' in namespace 'std' does not name a type
|    45 |             } catch (std::out_of_range& exception) {
|       |                           ^~~~~~~~~~~~
> Fix out_of_range without header

- plugins/filedump.c
- plugins/gstreamer_pcm.c
- plugins/opus.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
It is failed if compiling with `-Werror=format-truncation` with
`gcc v.10.2.0`.
error: '%04d' directive output may be truncated writing between 4
and 11 bytes into a region of size 9 [-Werror=format-truncation=]
|    80 |  snprintf(ymd, 9, "%04d%02d%02d", now_tm.tm_year + 1900,
|       |                    ^~~~
> Fix gcc-10 format-truncation warning

- examples/standalone/nugu_sdk_manager.cc
- include/base/nugu_network_manager.h
- include/clientkit/network_manager_interface.hh
- src/base/nugu_network_manager.c
- src/core/network_manager.cc
Currently, only the method of maintaining the connection was
supported, but due to a new requirement, a method of requesting
a connection only when necessary was added. Aka connectionless
or on-demand connection.
When a network connection request is received from a user, the
gateway list is received from the registry server and the network
status is changed to `READY`.
After receiving an event transmission request, the SDK connects to
the gateway server, transmits the event, and terminates the
connection after receiving all responses.
> network: add on-demand network type

- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
It change the shared_ptr to unique_ptr in NuguSDKManager
for improving memeory usage.
> nugu_sample:Change shared_ptr to unique_ptr

- include/clientkit/network_manager_interface.hh
- src/core/network_manager.cc
- src/core/network_manager.hh
For preventing unnecessary copy of string argument,
it change to const reference in some methods of NetworkManager.
> NetworkManager:Apply const reference in method arguments

- src/core/audio_input_processor.cc
- src/core/audio_input_processor.hh
Because the first argument of init method is sent by r-value
in WakeupDetector and SpeechRecognizer(derived of AudioInputProcessor),
it change to handle by universal reference for moving object(not copy).
> AudioInputProcessor:Apply move semantics in method arguments

- include/base/nugu_directive.h
- src/base/nugu_directive.c
The `const` is missing to some nugu_directive_XXX APIs.
> base: add missing const to directive APIs

- src/capability/audio_player_agent.cc
- src/core/routine_manager.cc
- src/core/routine_manager.hh
- tests/core/test_core_routine_manager.cc
It update the routine stop condition as adding the case when the received
directive has ASR.ExpectSpeech or AudioPlayer.Play in the middle progress.
> Routine:Update stop condition

- src/capability/text_agent.cc
- src/capability/text_agent.hh
The codes of overloading requestTextInput methods are almost same,
so, it refactor to remove duplication.
> Text:Refactor requestTextInput methods

- src/core/capability_manager.cc
Because, the routineActivity context info is only required when sent
events about Routine, it remove from makeContextInfo in CapabilityManager.
> context:remove unnecessary context info about Routine

- examples/standalone/capability_collection.hh
If the factory of specific capability is not exist in construction,
it occur std::bad_function_call error and the app is terminated.
So, it add the exception handling in factory usage.			
> nugu_sample:Fix bug about constructing capability

- include/clientkit/capability.hh
- include/clientkit/capability_interface.hh
- src/clientkit/capability.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
It add the updateCompactContext API in ICapabilityInterface for retrieving
the simple context information (like version) from each capability agent.
It update to use updateCompactContext API in makeContextInfo()
for removing implementation details about capability.
(It has to implement the check logic about Delegation in DelegationAgent.)
It extract getBaseContextInfo() from makeContextInfo() and
makeAllContextInfo() for removing duplicated codes.
> CapabilityManager:refactor composing context info

- src/capability/text_agent.cc
If the targetPlayServiceId in TextRedirect directive is empty,
it shouldn't send the playServiceId when sending TextInput event.
So. it update not to change to playServiceId,
if the targetPlayServiceId is empty.
> TextAgent:change handling TextRedirect directive

- src/capability/asr_agent.cc
- src/capability/text_agent.cc
- src/capability/text_agent.hh
When the ASR has foreground focus, if it try to send TextInput event,
the ASR is canceled and the focus is released.
In this situation, if background media exist, it has acquire foreground
focus even if not receiving response of TextInput event, so,
it cause abnormal behavior.
So, it update to relay focus in TextInput event, if the ASR has foreground
focus for maintaining focus until receiving response.
> TextAgent:Apply focus in sending TextInput event

- src/capability/mic_agent.cc
Even if the mic status is not changed,
it change to send SetMicSucceeded event.
> Mic:adjust send SetMicSucceeded event

- src/capability/system_agent.hh
by outside from public to private in SystemAgent.
> System:adjust access specifier

- src/capability/text_agent.cc
- src/capability/text_agent.hh
by outside from public to private in TextAgent.
It adjust method order in TextAgent source file to match with header.
> Text:adjust access specifier and method order

- src/capability/display_agent.cc
- src/capability/display_agent.hh
by outside from public to private in DisplayAgent.
It adjust method order in DisplayAgent source file to match with header.
> Display:adjust access specifier and method order

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
by outside from public to private in TTSAgent.
It adjust method order in TTSAgent source file to match with header.
> TTS:adjust access specifier and method order

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
by outside from public to private in AudioPlayerAgent.
It adjust method order in AudioPlayerAgent source file
to match with header.
> AudioPlayer:adjust access specifier and method order

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
by outside from public to private in ASRAgent.
It adjust method order in ASRAgent source file to match with header.
> ASR:adjust access specifier and method order

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
AudioPlayerAgent is blocked to media playback on foreground action
only if the suspend policy is `SuspendPolicy::STOP`.
> AudioPlayerAgent: modified suspend (pause policy)

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
When sending StopCommandIssued and PauseCommandIssued event,
if the focus is mixed with ASR, before receiving related directive,
it could chance to get foreground focus intermediately,
so it play media in very short term.
For preventing this abnormal situation, it apply flag not to play media
even if it has foreground focus until receiving response of event.
> AudioPlayer:update condition to skip intermediate foreground focus

- include/clientkit/focus_manager_interface.hh
- src/capability/text_agent.cc
- src/capability/tts_agent.cc
- src/core/focus_manager.cc
- src/core/focus_manager.hh
- tests/core/test_core_focus_manager.cc
In some case, it needs to convert FocusState to string and vice versa.
For preventing incorrect string usage, it defines the matched string
in FocusManager and add the related API.
> focus:add convertToFocusState in IFocusManager

- src/capability/audio_player_agent.cc
The content is not played when it is failed to send event with the
flag `skip_intermediate_foreground_focus` set.
> AudioPlayerAgent: fix the bug

- examples/standalone/capability/audio_player_listener.cc
- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
This event is occurred when the agent receives a pause directive, it
blocks content playback until another directive is received.
> AudioPlayerAgent: hold pause event

- src/core/playsync_manager.cc
If the postPoneRelease is called before releaseSyncImmediately,
the release is not activated until the continueRelease is called.
Because the requirement of releaseSyncImmediately is to release at once,
it update to active like that, even if the postPoneRelease is called.
> playsync:update releaseSyncImmediately condition

- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
The AudioPlayerAgent is support to control player directly as belows.
pause(bool direct_access = false)
resume(bool direct_access = false)
stop(bool direct_access = false)
> Audioplayer direct control

- examples/standalone/capability/audio_player_listener.cc
- include/capability/audio_player_interface.hh
- src/capability/audio_player_agent.cc
The AudioPlayerAgent is support now tell application why mediaplayer
is paused.
> AudioPlayerAgent: add pause reason

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
In so many case, when the specific play is stopped by user command,
TTS.Speak direcive which has not contain text are delivered from server.
Because the playsync has to be released immediatley in this situation,
it update to check whether TTS.Speak direcive has contain text or not,
so progressing release sync correctly.
> TTS:update TTS playsync release

- src/core/capability_manager.cc
- src/core/capability_manager.hh
Previously, when handling directive in onHandleDirective,
it sent command to all capability in every time by sendCommandAll.
Because, it's sufficient to send command once in each dialog,
it add the check flow for limiting sending command just once.
Some directives like System.Noop doesn't need to handle,
so, it add the check flow too.					
> CapabilityManager:Improve efficiency onHandleDirective

- src/capability/audio_player_agent.cc
It add to send AudioPlayerEvent::LOAD_DONE event,
when handling MediaPlayerEvent::LOADING_MEDIA_SUCCESS in mediaEventReport.
> AudioPlayer:add to send LOAD_DONE media event

- examples/standalone/nugu_sample.cc
Because, the runtime application arguments are applied after calling
handleArguments of NuguSampleManager, there exists the case
the custom model path is not applied in NuguSDKManager.
So, it adjust the order of creating NuguSDKManager after calling
handleArguments for applying application arguments correctly.
> nugu_sample:adjust NuguSDKManager creation order

- README.md
Because, the epd/kwd model files are included in sdk,
it remove the related guide in readme.
> Document:update README

- packaging/bionic/libnugu-examples.install
- packaging/bionic/libnugu.install
- packaging/xenial/libnugu-examples.install
- packaging/xenial/libnugu.install
It fix the install option of libnugu and libnugu-example.
> packaging:fix libnugu and libnugu-example install

- src/core/playsync_manager.cc
It revoke the change about releaseSyncImmediately,
because in some case, such condition is required.
> PlaySync:revoke change about releaseSyncImmediately

- src/capability/tts_agent.cc
Because the existing check logic was simply checked with a string,
there is a bug that it does not work properly when tags are included
in SKML.
So, modified it to check through a regular expression.
> capability: fix SKML empty string check logic

- src/capability/audio_player_agent.cc
- src/core/capability_manager.cc
- src/core/capability_manager.hh
In some case, there needs to reset some variables in CapabilityAgent
when the network is disconnected.
So, it implements onStatusChanged callback in CapabilityManager
and send the network_disconnected command to each Agent in above case.
In currently, the AudioPlayerAgent needs that command,
it update to handle as resetting skip_intermediate_foreground_focus.
> CapabilityManager:Handle Network Disconnected Status

- include/clientkit/playsync_manager_interface.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
- src/clientkit/playsync_manager_interface.cc
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the onStackChanged API in IPlaySyncManagerListener
which is possible to be notified playstack changes regardless sync state.
It define no-op methods about IPlaySyncManagerListener
for preventing unnecessary overriding.
> PlaySyncManager:Add onStackChanged API in IPlaySyncManagerListener

- examples/standalone/capability/speech_operator.cc
- examples/standalone/capability/speech_operator.hh
- examples/standalone/nugu_sdk_manager.cc
- include/capability/asr_interface.hh
- include/clientkit/directive_sequencer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/core/test_core_directive_sequencer.cc
If the cancel option is true, all directives corresponding to the
current dialog are canceled among the directives to be received in
the future. It also cancels directives that have already been
received but are still pending.
However, directives that have already been received and are in the
processing state (active state) are not canceled and remain.
In this case, it must be stopped manually via the corresponding
agent's function as needed.
> capability: add cancel option to stopRecognition

- include/clientkit/directive_sequencer_interface.hh
- src/capability/audio_player_agent.cc
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
To solve the timing issue, when the audio player state is changed
to play, a process has been added to check whether the corresponding
dialog-id has already been canceled.
> capability: add check for canceled dialog-id

- src/capability/tts_agent.cc
In the most case, the result of the stop play serivce is delivered by
TTS.Speak directive which does not contain any text data.
Because no TTS stream exist, there are no needs to play TTS.
So, it update to skip focus handling in the above case.
> TTS:update parsing TTS.Speak directive

- tests/core/test_core_playsync_manager.cc
It fix the test function prefix of PlaySyncManager
from PlayStackManager to PlaySyncManager.
> Playsync:fix PlaySyncManager test typo error

- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
`http2_network_remove_request_sync()` API is no more used.
> base: remove unused http2 network API

- src/capability/tts_agent.cc
For handling the empty text case (play stop) correctly when parsing
TTS.Speak directive, it needs to process full flows of parsingStop method.
So, it update to call the parsingStop method in parsingSpeak,
if it has to stop play caused by receiving the empty text.
> TTS:fix parsing TTS.Speak directive

- src/capability/tts_agent.cc
It remove the unused token variable in parsingStop.
> TTS:remove unused variable

- src/base/network/http2/http2_network.c
- src/base/network/http2/http2_network.h
- src/base/network/http2/http2_request.c
- src/base/network/http2/http2_request.h
- src/base/network/http2/v2_events.c
Change the HTTP2Network module to use request_id instead of a direct
HTTP2Request pointer to manage each HTTP2Request handle.
The request_id is assigned by the HTTP2Network module using the
`http2_network_add_request()` API.
> base: add request_id to manage http2 requests

- examples/standalone/capability/tts_listener.cc
- include/capability/tts_interface.hh
- src/capability/tts_agent.cc
As there are no state to handle TTS stopped case,
it add the TTS_SPEECH_STOP state in TTSState enum.
> TTS:Add TTS speech STOP state

- examples/capability_injection/main_capability_injection.cc
- examples/profiling/main_prof.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/simple_text/main_text.cc
- examples/simple_tts/main_tts.cc
- examples/standalone/nugu_sdk_manager.cc
- include/base/nugu_network_manager.h
- include/clientkit/network_manager_interface.hh
- src/base/nugu_network_manager.c
- src/core/network_manager.cc
When a connection attempt fails for the entire device-gateway
server list, there is no separate FAILED event and there is only
a DISCONNECT event, so it is difficult to determine the exact
status in the application.
To solve this problem, add a FAILED event, and when the application
receives this event, it checks the network status and tries to
connect again.
> network: add FAILED error status

- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
It extract the sendEventSpeechState from sendEventSpeechStarted,
sendEventSpeechStopped, sendEventSpeechFinished,
because that methods have same codes except event name and state.
> TTS:refactor sending speech state event

- include/clientkit/playsync_manager_interface.hh
- src/capability/display_render_helper.cc
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It update to append the another capability agent as requester
even if target playstack is already synced when calling prepareSync.
> PlaySync:update PlaySyncManager prepareSync

- include/clientkit/playsync_manager_interface.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It add the adjustPlayStackHoldTime API for adjusting playstack hold time.
(The default playstack hold time is 7 second.)
Because it has to be handled in specific case temporarily,
if the playstack is released, the hold time is reset to default by self.
> PlaySync:Add adjustPlayStackHoldTime API

- src/capability/display_agent.cc
- src/capability/display_agent.hh
It apply the Display Duration Option which is used to maintain display
during the time of an option after TTS finished.
> Display:Apply Display Duration Option

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
It update to close AudioPlayer display by app correctly.
Because, it has to stop TTS/media and related play simultaneously,
it execute to release play sync.
> AudioPlayer:Update to handle display close by app

- plugins/gstreamer_pcm.c
The audio sink is changed from `pulsesink` to `autoaudiosink`.
> plugin: change the gstreamer sink

- include/clientkit/playsync_manager_interface.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playsync_manager.cc
It add the restartHolding API for restarting playstack holding timer.
> PlaySync:Add restartHolding API

- include/capability/display_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
It add the refreshRenderingTimer API in IDisplayHandler
for refreshing display rendering hold timer.
> Display:Add refreshRenderingTimer API

- src/capability/display_agent.cc
- tests/core/test_core_playsync_manager.cc
It implements the stopRenderingTimer method in DisplayAgent
for maintaining display as clearing playstack hold timer.
The matched playstack is removed by closing display by user
or receiving another dialog from server.
> Display:Implements stopRenderingTimer

- src/core/focus_manager.cc
- tests/core/test_core_focus_manager.cc
The user could hold the focus via focus manager, and then
it blocks the lower priority focus get audio resource
until unhold it. It is auto unhold when the focus type is
requested or unhold focus directly call.
> focus: focus hold

- include/clientkit/playsync_manager_interface.hh
- src/core/playstack_manager.cc
- src/core/playstack_manager.hh
- src/core/playsync_manager.cc
- src/core/playsync_manager.hh
- tests/core/test_core_playstack_manager.cc
- tests/core/test_core_playsync_manager.cc
It add the setDefaultPlayStackHoldTime method in IPlaySyncManager
for changing default playstack hold time. (default : 7sec).
The main purpose is to customize default playstack hold time by PoC.
> PlaySync:Add setDefaultPlayStackHoldTime API

- src/capability/display_agent.cc
- src/core/playstack_manager.cc
- src/core/playsync_manager.cc
- tests/core/test_core_playsync_manager.cc
It fix not to remove the playstack holding for media paused
when another playstack is added during long timer is activating.
> PlaySync:Fix PlayStack Holding in Media Paused

- include/clientkit/directive_sequencer_interface.hh
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
- tests/core/test_core_directive_sequencer.cc
Added API for finding directives by 'namespace.name' in pending list
to handle exceptional scenario.
> core: add directive find API to sequencer

- src/capability/tts_agent.cc
When processing TTS.Stop directive, as the directive is destroyed by Agent
itself in some case, it apply the destroy_directive_by_agent option.
Also, when handling onSyncState callback, as the is_finish flag is not
sufficient to check TTS stopped, it change to check the media play state.
> TTS: apply destroy directive by agent option

- examples/standalone/capability/audio_player_listener.hh
- examples/standalone/capability_collection.cc
- include/capability/audio_player_interface.hh
- include/capability/display_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/display_interface.cc
It divide the IAudioPlayerDisplayListener from IAudioPlayerListener.
It change the API for setting/removing IAudioPlayerDisplayListener.
* from setListener to setDisplayListener
* from removeListener to removeDisplayListener
It define the no-op methods of IDisplayHandler for preventing
unnecessary methods overriding even if those are not used.
> AudioPlayer:refactor AudioPlayer Display Interface

- externals/0001_curl_find_nghttp2.patch
- src/CMakeLists.txt
update the nghttp2 library v1.40.0 to v1.44.0
> externals: update nghttp2 to v1.44.0

- src/core/speech_recognizer.cc
The EPD library updated to set the input and output data format using
epd_param.
> core: add input/output type to epd_param

- src/capability/message_agent.cc
It add to call the same overriding base method in initialize
of MessageAgent for initializing variables of base class.
> Message:Add to call base initialize

- include/capability/message_interface.hh
- src/capability/message_agent.cc
- src/capability/message_agent.hh
/**
* @brief Report changes in the speech state to the user.
* @param[in] state message state
* @param[in] dialog_id dialog request id
*/
virtual void messageStateChanged(MessageState state, const std::string& dialog_id) = 0;
> Message: added playback state event

- include/capability/message_interface.hh
- src/capability/message_agent.cc
- src/capability/message_agent.hh
Token and received_time are added to playback state event.
> Message: modified playback state event

- src/capability/phone_call_agent.cc
The call state is `PhoneCallState::IDLE` when the user calls on
phone directly.
> PhoneCall: modified CallEstablished

- src/capability/tts_agent.cc
Besides text, because there are some xml tags exist for handling,
It update the empty text check logic about Speak directive.
Also, it update to set the speak_dir variable null, when parsing Stop
if TTS not playing state for preventing dangling pointer problem.
(In playing state, it set to null by focus handling).
> TTS:update empty text check in Speak directive

- include/base/nugu_encoder.h
- src/base/nugu_decoder.c
- src/base/nugu_encoder.c
- tests/CMakeLists.txt
- tests/test_nugu_encoder.c
Add an encoder driver base implementation to support various encoding
types such as SPEEX and OPUS.
> base: add encoder driver

- plugins/gstreamer_pcm.c
There is a bug where if the user sets the volume to 0
before playback, it won't be set.
> Plugins: Modified the gstreamer pcm

- include/capability/tts_interface.hh
- src/capability/tts_agent.cc
- src/capability/tts_agent.hh
It add the setMute API in TTS interface for controlling PCM mute.
In currently, that API is activated when using gstreamer_pcm plugin only.
> TTS:Add setMute API

- CMakeLists.txt
add `-fmacro-prefix-map` option to strip the path from filename
> build: enhance __FILE__ macro

- src/capability/tts_agent.cc
I update to stop another foreground focus in parsing Stop directive
when the current TTS is not playing state.
> TTS:update parsing Stop

- src/capability/display_agent.cc
- src/capability/display_agent.hh
- src/capability/display_render_helper.cc
- src/capability/display_render_helper.hh
It update the handling template history control
to manage whether the template is rendered or not.
> Display:Update handling history control

- src/capability/audio_player_agent.cc
- src/capability/audio_player_agent.hh
Add a `cancelDirective` handler to AudioPlayer agent to remove the
`playServiceId` from playStack when the preprocessed directive is
canceled.
> add cancelDirective to AudioPlayer

- src/capability/tts_agent.cc
- src/core/directive_sequencer.cc
fix double free issue on `cancelDirective()` handler and
`cancel()` API in the directive sequencer.
> fix double free on cancelDirective

- src/capability/audio_player_agent.cc
The explicit pause is added when the media player is paused by user.
> AudioPlayerAgent: added explicit pause

- src/base/nugu_plugin.c
If `-1` is returned in the `init` handler of a specific plug-in
during the initialization process of all plug-ins, the plug-in is
checked for removal and is removed from the plug-in list after
initialization.
At this time, when searching with the `nugu_plugin_find` API in
other plugins, the list item may be `null` in the case of a plugin
scheduled to be removed.
Plugin A: return -1 in init()
Plugin B: nugu_plugin_find('A') in init() -> crash
> base: add null check to plugin_find

- src/capability/display_agent.cc
- src/capability/display_agent.hh
It update to apply the InteractionControl in ControlScroll directive.
It's finished when ControlScrollSucceeded event is sent.
> Display:Apply InteractionControl in ControlScroll

- include/clientkit/speech_recognizer_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/core/speech_recognizer.cc
When recognizing the end of a voice, a separate end attachment packet
was transmitted without body data, but it was inefficient because it
had to send an unnecessary header.
In order to reduce unnecessary network transmission, it has been
modified to send the end mark in the header together with the last
data when recognizing the end of the voice.
> fix last attachment data for ASR

- .cppcheck_suppress.txt
- examples/capability_injection/battery_agent.hh
- examples/standalone/capability/display_listener.cc
- examples/standalone/capability/sound_listener.hh
- examples/standalone/nugu_sample_manager.cc
- include/clientkit/capability.hh
- src/capability/asr_agent.cc
- src/capability/audio_player_agent.cc
- src/capability/routine_agent.cc
- src/capability/session_agent.hh
- src/clientkit/nugu_client.cc
- src/core/audio_recorder_manager.cc
- src/core/audio_recorder_manager.hh
- src/core/capability_manager.cc
- src/core/capability_manager.hh
- src/core/directive_sequencer.cc
- src/core/playstack_manager.hh
- src/core/speech_recognizer.hh
- src/core/wakeup_detector.hh
- tests/core/test_core_playstack_manager.cc
It fix the some issues of Cppcheck analysis results.
It add the suppression cases because it's not effective.
* noCopyConstructor
* noOperatorEq
> Fix Cppcheck analysis results

- examples/capability_injection/main_capability_injection.cc
- examples/profiling/main_prof.cc
- examples/response_filter/filter.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/simple_play/main_play.cc
- examples/simple_text/main_text.cc
- examples/simple_tts/main_tts.cc
It add the override keyword on methods which are inherited from parent.
> examples:Add override keyword

- include/base/nugu_event.h
- include/clientkit/capability.hh
- include/clientkit/speech_recognizer_interface.hh
- src/base/network/dg_server.c
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
- src/base/nugu_event.c
- src/capability/asr_agent.cc
- src/clientkit/capability.cc
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
Fixed attachment mime type information that were used as fixed
values so that they can be set through API.
> fix mime_type to configurable

- include/base/nugu_encoder.h
- include/clientkit/speech_recognizer_interface.hh
- src/base/nugu_encoder.c
- src/capability/asr_agent.cc
- src/core/speech_recognizer.cc
- src/core/speech_recognizer.hh
- tests/test_nugu_encoder.c
Add API for codec and mime_type to encoder module.
And add the 'is_end' parameter to the `.encode` API so that the
encoder plugin can check if that pcm is the last or not.
> base: fix encoder module

- plugins/gstreamer.c
- plugins/portaudio.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
Lowered the priority of the PortAudio PCM plugin so that the
Gstreamer plugin works by default.
PCM plugin priority:
gstreamer_pcm (default) -> Default PCM driver
gstreamer_recorder (default) -> Default recorder driver
portaudio (default + 1)
portaudio_pcm_async (default + 2)
portaudio_pcm_sync (default + 3)
portaudio_recorder (default + 2)
> plugins: adjust pcm driver priority

- examples/standalone/capability_collection.cc
- examples/standalone/capability_collection.hh
It add the getCapabilityListener method in CapabilityCollection
which is possible to retrieve the matched capability listener instance.
> nugu_sample:Add getCapabilityListener in CapabilityCollection

- examples/standalone/capability/speaker_listener.cc
- examples/standalone/capability/speaker_listener.hh
- examples/standalone/nugu_sdk_manager.cc
- examples/standalone/nugu_sdk_manager.hh
In previous, the SpeakerController compose volume/mute controls by self
using by TTS/AudioPlayer handlers.
Because, those controls are composed in SpeakerListener
by CapabilityCollection, in result, it generated the duplication.
So, it refactor to use the pre-composed volume/mute controls
of SpeakerListener in SpeakerController singly.
> nugu_sample:Refactor SpeakerController setup

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
It update to handle the asrContext during parsing ExpectTyping directive.
The asrContext as including playServiceId and domainTypes has to be
fetched by ASRAgent when sending recognize event if values exist.
> Text:Update Text Interface 1.6 spec

- include/clientkit/nugu_auth.hh
- src/clientkit/nugu_auth.cc
- tests/clientkit/CMakeLists.txt
- tests/clientkit/test_clientkit_auth.cc
add authentication API to support OAuth2 discovery, client_credentials
and token refresh feature.
> clientkit: add Authentication API

- include/clientkit/nugu_auth.hh
- src/clientkit/nugu_auth.cc
- tests/clientkit/test_clientkit_auth.cc
add device gateway registry and template server uri getter to NuguAuth
module.
> clientkit: add uri information getter to auth

- include/clientkit/nugu_runner.hh
- src/clientkit/nugu_runner.cc
- tests/clientkit/test_clientkit_nugu_runner.cc
GMainLoop is guaranteed to preempt the context and changes the default
policy so that the blocking method waits until execution is complete.
A timeout can be used if necessary.
> clientkit: modify nugu runner policy

- src/capability/message_agent.cc
- src/capability/message_agent.hh
- src/capability/phone_call_agent.cc
- src/capability/phone_call_agent.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
As the InteractionControl information is required
when sending the related events in some agents,
it update to include the payload of InteractionControl at that time.
> InteractionControl:Update handling InteractionControl

- src/clientkit/nugu_http_rest.cc
HttpRest has no error checking when the network is unavailable.
This can be hangup caused by access to null pointer.
> clientkit: fix http rest issue

- src/capability/capability_factory.cc
As the code of template instantiation for capability agent is very long,
it define to macro for using simply.
> CapabilityFactory:clean code about template instantiation

- src/capability/audio_player_agent.cc
- src/capability/display_agent.cc
- src/capability/display_agent.hh
It add the condition not to release PlaySync
if the current playstack is used in Display.
> AudioPlayer:fix handling cancel directive

- src/capability/display_agent.cc
- src/capability/display_agent.hh
It fix not to release play sync when the media is stacked
when the display history control is progressing.
> Display:Fix handling history control

- src/capability/audio_player_agent.cc
It update to clear the PlayStackControl info after the matched play sync
is released for preventing unnecessary usage in AudioPlayerAgent.
> AudioPlayer:update PlayStackControl info management

- include/base/nugu_audio.h
- include/base/nugu_pcm.h
- include/base/nugu_player.h
- include/clientkit/media_player_interface.hh
- src/base/nugu_audio.c
- src/base/nugu_pcm.c
- src/base/nugu_player.c
- src/capability/audio_player_agent.cc
- src/capability/tts_agent.cc
- src/core/media_player.cc
- src/core/media_player.hh
- src/core/tts_player.cc
- src/core/tts_player.hh
- tests/test_nugu_pcm.c
- tests/test_nugu_player.c
The audio volume is controlled by speaker's interface via audio
attribute. Categorized with reference to Android audio attribute.
> audio: add audio attribute

- include/clientkit/media_player_interface.hh
- src/capability/audio_player_agent.cc
- src/capability/message_agent.cc
- src/capability/tts_agent.cc
- src/core/tts_player.cc
- src/core/tts_player.hh
> clientkit: fix the code convention

- examples/standalone/nugu_sdk_manager.cc
- include/capability/text_interface.hh
- src/capability/text_agent.cc
- src/capability/text_agent.hh
It add the source field which indicate info to trigger TextInput event.
It update to handle the source field when parsing TextSource directory.
> Text:apply TextInput event latest spec

- examples/standalone/capability_collection.cc
- include/base/nugu_audio.h
- include/capability/speaker_interface.hh
- src/base/nugu_audio.c
- src/capability/speaker_agent.hh
The speaker type is synchronized with audio property name and value.
> speaker: sync with audio property

- include/clientkit/nugu_client.hh
- src/clientkit/nugu_client.cc
- src/clientkit/nugu_client_impl.cc
- src/clientkit/nugu_client_impl.hh
The audio resources is managed by framework and the focus is not
handled in capability agent all the time. For convenience usage, the focus
manager interface is exposed to the clientkit.
> clientkit: expose focus manager interface

- include/base/nugu_audio.h
- include/capability/speaker_interface.hh
- src/base/nugu_audio.c
- src/capability/speaker_agent.cc
- src/capability/speaker_agent.hh
- tests/CMakeLists.txt
- tests/test_nugu_audio.c
- tests/test_nugu_pcm.c
- tests/test_nugu_player.c
The names of audio properties are framework-dependent. And the nugu
speaker synchronizes the name with the default audio properties.
> base: set audio property's name

- examples/standalone/capability/chips_listener.cc
- examples/standalone/capability/chips_listener.hh
- include/capability/chips_interface.hh
- src/capability/chips_agent.cc
When the onReceiveRender call is propagated in several times,
as the argument is moved by universal reference, it can only be used once.
So, it change the argument type to const reference for multiple usages.
> Chips:change onReceiveRender argument type

- include/base/nugu_buffer.h
- src/base/nugu_buffer.c
- tests/test_nugu_buffer.c
Add `nugu_buffer_add_byte` and `nugu_buffer_set_byte` functions
to manipulate the nugu_buffer by byte.
> base: add byte buffer manipulation to nugu_buffer

- src/clientkit/dialog_ux_state_aggregator.cc
- tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
It fix to include chips info in onStateChanged callback
only if the current dialog_id is matched.
> DialogUXStateAggregator: fix handling chips info

- src/clientkit/dialog_ux_state_aggregator.cc
- tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
It fix the issues detected by cppcheck about variable initialization.
> DialogUXStateAggregator: fix issues detected by cppcheck

- src/clientkit/dialog_ux_state_aggregator.cc
- tests/clientkit/test_clientkit_dialog_ux_state_aggregator.cc
Even if the multi-turn is deactivated, the chips info may be required.
As the deletion timing of chips info is ambiguous, instead of explicitly
deleting it, it is used after checking dialog id validity.
> DialogUXStateAggregator: adjust chips info management

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
It add to release ASR_DM_FOCUS_TYPE focus if a multi-turn is deactivated.
It add the progress check flag in executeOnNoneAction method
for preventing recursive call during releasing focus.
> ASR: fix DM focus release

- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
It move the class declaration to source.
It change the listener type from raw point to unique_ptr.
It adjust the construction time which is created in ASRAgent constructor.
It update to use const reference parameter to maintain origin value.
> ASR: refactor FocusListener

- include/base/nugu_http.h
- src/base/nugu_http.c
- tests/test_nugu_http.c
Add HTTP download API to support file download from HTTP URL.
This API works asynchronously and provides callbacks to know the
progress status of the download.
> base: add HTTP download API

- tests/test_nugu_http.c
Fix the http test case to avoid external network connection when the
environment variable is not set.
> tests: fix http test case

- packaging/focal/control
Ubuntu 20.04(focal) version uses gcc 9.4.0. Therefore, libasan5
should be used, but libasan4 (for gcc v7) was set incorrectly.
Signed-off-by: GitHub <noreply@github.com>
> packaging: fix libasan version in 20.04(focal)

- include/clientkit/speech_recognizer_aggregator_interface.hh
- src/clientkit/speech_recognizer_aggregator.cc
- src/clientkit/speech_recognizer_aggregator.hh
- tests/clientkit/CMakeLists.txt
- tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
It add the SpeechRecognizerAggregator which is composed for operating
wakeup detection and speech recognition process conveniently.
It define ISpeechRecognizerAggregator, ISpeechRecognizerAggregatorListener
interface in clientKit to provide publicly.
> clientkit: add SpeechRecognizerAggregator

- include/clientkit/speech_recognizer_aggregator_interface.hh
- src/clientkit/speech_recognizer_aggregator.cc
- src/clientkit/speech_recognizer_aggregator.hh
- tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
As the setWakeupModel result is required in some situation,
it change the return type from void to bool.
> SpeechRecognizerAggregator: change setWakeupModel return type

- src/clientkit/nugu_runner.cc
add `d->done` value check before blocking-wait to avoid waiting if
the runner-job is already done.
> clientkit: fix nugu_runner wait blocking issue

- include/capability/chips_interface.hh
It fix not to be occurred ODR(one definition rule) warning in ChipsInfo
as declaring struct name explicitly when building in ubuntu 22.04(jammy).
> Chips: fix ChipsInfo ODR issue

- tests/clientkit/CMakeLists.txt
- tests/core/CMakeLists.txt
It fix not to include the test target source duplicately
as it's already linked by lnugu.
It could prevent ODR issue which is occurred from ASAN.
> tests: remove test target source duplication

- src/clientkit/speech_recognizer_aggregator.cc
- tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
It adjust the validation check condition which to check
the only required handler on a case by case.
As a result, it's possible to execute the startListening
even if the WakeupHandler is not set.
> SpeechRecognizerAggregator: adjust validation check

- plugins/speex.c
The memory for encoder_data is allocated but not freed, resulting leak.
(It only free the buffer currently.)
So, it fix to free the allocated memory in destroyed time.
> plugins: fix memory leak of speex

- plugins/opus_encoder.c
The ogg_packet.packet which memory is allocated before calling
ogg_stream_packetin is not freed, so it result memory leak.
So, it fix to free the allocated memory after calling ogg_stream_packetin.
Because the ogg_packet data is copied in ogg_stream_packetin internally,
it's no problem manipulate ogg_packet after calling ogg_stream_packetin.
> plugins: fix memory leak of opus encoder

- examples/standalone/clientkit/speech_recognizer_aggregator_listener.cc
- include/clientkit/wakeup_interface.hh
- tests/clientkit/test_clientkit_speech_recognizer_aggregator.cc
It add the WakeupDetectState WAKEUP_IDLE to indicate the initial state.
> wakeup: add wakeup idle state

- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
- src/core/wakeup_handler.cc
In previously, even if the wakeup is stopped by user explicitly,
the state is WakeupDetectState::WAKEUP_FAIL.
As it's judged unreasonable, it change to WakeupDetectState::WAKEUP_IDLE.
> wakeup: change handling wakeup stop state

- src/base/network/http2/http2_network.c
Add missing `curl_multi_remove_handle()` call to cleanup logic for
incomplete HTTP/2 requests.
> base: fix memory leak in http2 network module

- .github/workflows/pull_request.yaml
- examples/standalone/capability/tts_listener.cc
- examples/standalone/capability/tts_listener.hh
- examples/standalone/nugu_sdk_manager.cc
- src/capability/display_agent.cc
- src/capability/display_render_helper.cc
- src/capability/message_agent.cc
- src/core/audio_recorder_manager.cc
- src/core/focus_manager.cc
- tests/core/test_core_playsync_manager.cc
- tests/core/test_core_routine_manager.cc
It upgrade the clang-tidy-action to v1.2 activating on ubuntu 20.04.
It fix to use const/universal reference for copied value usage detection.
* performance-for-range-copy
* performance-unnecessary-value-param
It suppress the C-style variadic function usage because it seems fair use.
(It would upgrade clang-tidy-action to be able to handle this properly.)
* cert-dcl50-cpp
> upgrade clang-tidy-action to v1.2

- CMakeLists.txt
- include/base/nugu_plugin.h
- src/base/nugu_plugin.c
- tests/test_nugu_plugin.c
Apply the `-fanalyzer` compile option to enable static analyzer.
This option only works for C language (C++ is currently recommended)
https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Static-Analyzer-Options.html
> build: apply -fanalyzer compile option

- src/capability/asr_agent.cc
The spec is the isAddListen field is added in asrContext payload.
Because the asrContext payload is handled by object itself,
there are no need to handle the added field directly.
So, it just update the capability version to 1.7.
> ASR: apply ASR interface v1.7 spec

- include/clientkit/nugu_auth.hh
- src/clientkit/nugu_auth.cc
- tests/clientkit/test_clientkit_auth.cc
Add `discovery(callback)` API to support async requests to the
auth module. The response callback can get the result of discovery
success or failure just like the sync API.
> clientkit: add async API to auth discovery

- src/capability/text_agent.cc
- src/capability/text_agent.hh
It add to send the interactionControl payload in TextInput event if exist.
It update the TextInputParam struct to handle interactionControl.
> Text: add interactionControl in TextInput event

- src/capability/display_agent.cc
- src/capability/display_agent.hh
It add to send the interactionControl payload about response events
of ControlScroll directive.
* ControlScrollSucceeded
* ControlScrollFailed
> Display: add interactionControl in response events

- CMakeLists.txt
Apply the default link options used for debian packaging builds.
The link options can be checked with the `dpkg-buildflags` command,
and the options according to the distribution version are as follows.
bionic
LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro
focal
LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro
jammy
LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects
-flto=auto -Wl,-z,relro
> build: apply debian packaging default link option

- include/base/nugu_buffer.h
- include/base/nugu_directive.h
- include/base/nugu_pcm.h
- include/clientkit/routine_manager_interface.hh
- include/clientkit/wakeup_interface.hh
- src/base/network/http2/multipart_parser.h
- src/base/network/http2/v2_events.c
- src/base/network/http2/v2_events.h
- src/core/directive_sequencer.cc
- src/core/directive_sequencer.hh
Add missing `#include <...>` to header files.
> add missing include to header files

- CMakeLists.txt
- nugu.pc.in
Adds SDK Libraries Only, Plugin Only, and Examples Only build options so that developer can manually select a build target using the build options.
This makes it easy to set the target item when packaging. The options are as follows and should not be used together.
-DENABLE_LIBRARY_ONLY=ON (Default OFF)
Build the NUGU SDK library and TC. Install only SDK header
and library. Same as libnugu.deb and libnugu-dev.deb.
-DENABLE_PLUGINS_ONLY=ON (Default OFF)
Build and install the plugins directory with system installed
NUGU SDK library. Same as libnugu-plugins-default.deb.
-DENABLE_EXAMPLES_ONLY=ON (Default OFF)
Build and install the examples directory with system installed
NUGU SDK library. Same as libnugu-examples.deb.
> build: add option for library, plugins, examples

- src/capability/audio_player_agent.cc
It fix to parse UpdateMetadata directive correctly.
> AudioPlayer: fix parsing UpdateMetadata directive

- CMakeLists.txt
add `ASSET_DIR` option to CMakeLists.txt to use libnugu NUGU_ASSET_PATH definition in libnugu-examples package.
> build: add ASSET_DIR option

- CMakeLists.txt
- plugins/CMakeLists.txt
- src/CMakeLists.txt
The speex plugin requires nugu-epd dependency.
> build: add nugu-epd dependency to plugin

- .checkpatch.conf
- .github/workflows/doxygen.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
Node.js v12 is deprecated in Github action. So need to update related Github actions.
> build: update action version

- .github/workflows/codeql-analysis.yaml
ubuntu-latest now points to 22.04 instead of 20.04. However, the codeql action has an issue in 22.04, so it is changed to use 20.04.
> fix CodeQL action error

- include/clientkit/routine_manager_interface.hh
- src/capability/routine_agent.cc
- src/capability/routine_agent.hh
- src/core/routine_manager.cc
- src/core/routine_manager.hh
- tests/core/test_core_routine_manager.cc
It add/update the RoutineManager API to respond to routine interface 1.3.
It compose the RoutineManager test to implement API functions.
New Added API
* IRoutineManagerListener
- onActionTimeout()
* IRoutineManager
- move()
- getCurrentActionToken()
- getCountableActionSize()
- getCountableActionIndex()
- isConditionToCancel()
- isMuteDelayed()
- presetActionTimeout()
- setPendingStop()
- hasToSkipMedia()
> Routine: add/update RoutineManager API

- include/capability/routine_interface.hh
- src/capability/asr_agent.cc
- src/capability/asr_agent.hh
- src/capability/audio_player_agent.cc
- src/capability/routine_agent.cc
- src/capability/routine_agent.hh
- src/capability/tts_agent.cc
It apply the Routine Interface v1.3 in RoutineAgent and related agents.
It update the directive post-processing condition in TTSAgent.
It update the media foreground focus skip condition in AudioPlayerAgnet.
main features
* It could move to the previous and next action.
* It could handle the media in the middle actions.
* The media is played for the duration of the action timeout.
* The action type BREAK is added to hold routine during mute delay.
> Routine: apply Routine Interface v1.3

- src/base/nugu_log.c
The environment variable override check logic was missing in some of the getter APIs of the log module.
> base: add missing override check logic to log

- src/clientkit/nugu_auth.cc
If `response->body` is null due to an error, an exception occurs in the string conversion process.
To prevent this, added a null check and modified it to return an error.
> clientkit: add NULL check to auth module

- include/clientkit/nugu_http_rest.hh
- src/base/nugu_http.c
- src/clientkit/nugu_http_rest.cc
When memory is allocated, freed, and re-allocated, the same address can be allocated, so change to use a structure instead of a map through an address.
> clientkit: replace map in nugu_http to struct

- examples/standalone/capability/bluetooth_listener.cc
- examples/standalone/capability/bluetooth_listener.hh
- include/capability/bluetooth_interface.hh
- src/capability/bluetooth_agent.cc
- src/capability/bluetooth_agent.hh
A2DP streaming is processed like audio player in the sdk. It is paused when keyword is detected and tts is played. It is also resumed when tts is playing finished. For this, add focus to the bluetooth.
> capability: add focus for bluetooth

- src/capability/bluetooth_agent.cc
- src/capability/bluetooth_agent.hh
The bluetooth focus should not acquire when processing the multi-turn and the routine situation.
> capability: skip foreground action

- src/core/wakeup_detector.cc
- src/core/wakeup_detector.hh
The event `WakeupState::DETECTED` is ignored when application requests stop and start repeatly during load kwd model file in `kwd_initialize`. Therefore, preload kwd model file in `WakeupDetector::initialize`.
> core: preload kwd model file

- examples/capability_injection/main_capability_injection.cc
- examples/profiling/main_prof.cc
- examples/response_filter/main.cc
- examples/simple_asr/main_asr.cc
- examples/simple_text/main_text.cc
- examples/simple_tts/main_tts.cc
- examples/standalone/nugu_sample_manager.cc
- examples/standalone/nugu_sdk_manager.cc
- plugins/filereader.c
- plugins/gstreamer_recorder.c
- plugins/portaudio.c
- plugins/portaudio_recorder.c
- src/base/network/http2/directives_parser.cc
- src/base/nugu_http.c
- src/base/nugu_log.c
- src/base/nugu_network_manager.c
- src/base/nugu_plugin.c
- src/base/nugu_prof.c
- src/capability/system_agent.cc
- tests/test_nugu_uuid.c
Fix following issues
- the value returned by this function should be used [cert-err33-c]
- The parameter must not be null [clang-analyzer-cplusplus.StringChecker]
> fix issues detected by clang-tidy

- src/core/speech_recognizer.cc
The encoder is sometimes returns encoded data with size 0 and performs incorrect process ASR communication.
> core: fix record data notification

- .github/workflows/codeql-analysis.yaml
- .github/workflows/doxygen.yaml
- .github/workflows/macos.yaml
- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
Upgrade following github action script versions
- `actions/*@v3` -> `actions/*@v4`
- `github/codeql-action/*@v2` -> `github/codeql-actions/*@v3`
> action: upgrade action versions

- CMakeLists.txt
- src/base/CMakeLists.txt
To fix macOS build error, add following changes
- add RapidJSON pkg-config
- fix GCC compiler cflags
> build: fix macOS build error

- .gitignore
- CMakeLists.txt
- include/base/nugu_plugin.h
- plugins/CMakeLists.txt
- plugins/dummy.c
- plugins/filedump.c
- plugins/filereader.c
- plugins/gstreamer.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
- plugins/opus.c
- plugins/opus_encoder.c
- plugins/portaudio.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
- plugins/speex.c
- src/CMakeLists.txt
- src/base/builtin.h.in
- src/base/nugu_plugin.c
- src/clientkit/nugu_client_impl.cc
- tests/plugin_nugu.c
- tests/plugin_nugu_custom.c
Modified plugin architecture to support embedding(built-in) in SDK
library instead of separate shared library.
Just add build options to the built-in target plugins as shown below.
cmake ... -DENABLE_BUILTIN_PLUGIN="opus,dummy,speex"
> fix plugin architecture

- plugins/speex.c
add `encoded_size` check logic.
> plugin: add size check logic to speex

- src/core/audio_recorder_manager.cc
- src/core/audio_recorder_manager.hh
To fix thread issue for `nugu_recorder_start/stop`, use `invokeMethod` in `NuguRunner` module.
> core: fix AudioRecorderManager to use runner

- CMakeLists.txt
- src/base/nugu_uuid.c
Replaced the API used to generate random strings and SHA1 strings with the API provided by `glib` instead of `openssl`.
* RAND_bytes -> g_rand
* SHA1 -> g_checksum
> base: change openssl based SHA1 to g_checksum

- plugins/opus_encoder.c
- plugins/speex.c
add missing `static` to internal functions to avoid duplicate symbol error
> plugins: add missing 'static' to function

- examples/profiling/main_prof.cc
- include/base/nugu_prof.h
- include/base/nugu_uuid.h
- plugins/filedump.c
- plugins/filereader.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
- plugins/opus.c
- plugins/opus_encoder.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
- plugins/speex.c
- src/base/network/http2/threadsync.c
- src/base/network/http2/v1_ping.c
- src/base/nugu_log.c
- src/base/nugu_network_manager.c
- src/base/nugu_prof.c
- src/base/nugu_recorder.c
- src/base/nugu_uuid.c
- src/capability/display_agent.cc
- src/capability/display_render_helper.cc
- tests/test_nugu_uuid.c
Fix following time API to support WIN32
- gettimeofday() -> g_get_real_time()
- clock_gettime() -> g_get_real_time()
Add ifdef macro to support WIN32
- gmtime_r / gmtime_s
- localtime_r / localtime_s
- srandom / srand
- random / rand
> fix time and random API to portable

- src/capability/tts_agent.hh
change `using` to `typedef struct`.
> capability: add TTSAgent build error on WIN32

- src/core/tts_player.cc
Remove the `(NuguAudioProperty)` casting from TTSPlayer constructor
> core: remove casting in the TTSPlayer

- plugins/filedump.c
- plugins/filereader.c
- plugins/gstreamer_pcm.c
- plugins/gstreamer_recorder.c
- plugins/opus.c
- plugins/portaudio_pcm_async.c
- plugins/portaudio_pcm_sync.c
- plugins/portaudio_recorder.c
Disable the symbolic link file generation for dump file on WIN32 platform.
> plugins: disable link for dump file on WIN32

- CMakeLists.txt
Fix the `BUILTIN_PLUGIN` feature to support string default value in the WIN32 environment.
The `OPTION()` only support `ON` and `OFF` for default value. So change to `SET()`.
> build: fix BUILTIN_PLUGIN feature

- src/base/nugu_equeue.c
- src/base/nugu_prof.c
Fix a bug using pthead mutex without initializing it.
> base: initialize mutex

- CMakeLists.txt
- externals/CMakeLists.txt
Add `ENABLE_BUILTIN_NJSON` feature option to provide `njson` library dependency option.
Default is ON (use sources from `externals/njson` submodule). And if option is OFF, use the `njson.pc` pkg-config file.
> build: add BUILTIN_NJSON feature

- src/base/nugu_curl_log.c
To fix crash for CRLF data, skip the data modification if the data is only include CRLF data.
> base: fix curl log to skip CRLF data

- src/core/media_player.cc
- src/core/media_player.hh
It change to send update position callback even if the media is paused.
> fix media player position handling

- src/core/network_manager.cc
- src/core/network_manager.hh
As it's not possible to parse token of not nugu usage types,
so when token parsing failure, it determine to connection oriented mode.
> update network connection oriented mode check

- src/core/media_player.cc
If only the AudioPlayer is received instead of receiving a voice response from the server in the order of TTS and AudioPlayer, polling timer is not work.
> core: update position
